### PR TITLE
Improve WebView & UI

### PR DESCRIPTION
**Pull request by drkameleon**
# Description

Currently, we have [**webview-based UI**](https://arturo-lang.io/documentation/library/ui/webview/) support (based on an older version of [Serge Zaitsev's Webview](https://github.com/webview/webview) library, Chrome-based UI (basically, using the already-installed Chrome-compatible chrome to show any URL/page) & [**server**](https://arturo-lang.io/documentation/library/net/serve/) support (based roughly on Nim's standard library [AsyncHttpServer](https://nim-lang.org/docs/asynchttpserver.html)).

Both parts *do* work, with a few asterisks:

- we are currently using an older C-only version of the Webview library - which is a) good, because it's pure C, b) bad, because there are changes that are great and *should* be incorporated
- the distinction between the different library functions (`webview`, `serve`, `serve.chrome`) is a bit weird and confusing
- the integration between the "backend" (Arturo itself) and the webview is a bit messy (basically, it kinda works, but even I don't remember exactly how... lol) - this should be cleaned up, or re-written from scratch
- the server part and the webview don't work together - mainly, having to do with blocking threads (for example, for Grafito, the ideal scenario would be: start a server, and open up a webview - non-Chrome - window pointing to that server. No big deal. But it still doesn't work)

Given that the UI part (and especially webview-based UI functionality) seems to be *the* future of UI apps - or, at least, a good part of them, this has to be worked on.

Related: https://github.com/arturo-lang/arturo/pull/275
Also related to: https://github.com/arturo-lang/aguila

Fixes: #207 #261

## Type of change

- [X] Code cleanup
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

### CODE REVIEW

**Comment by drkameleon** [comment]
Definitely of interest: https://github.com/webview/webview/pull/662

...as well as: https://github.com/petabyt/webviewc

**Comment by drkameleon** [comment]
Looks like I ended up creating a new repo, just for the Webview migration to Nim (lol):

https://github.com/drkameleon/nim-webview

**Comment by dumblob** [comment]
Thanks, I've subscribed now for repo updates :wink:.

**Comment by drkameleon** [comment]
I think this PR has far - faaar - overgrown its initial purpose.

I'm merging it - and will clean up various details as they pop up (hopefully not) from the master branch, and on our way to the next release.

So...

Ready to merge! 🚀

**Pull request merged**
