### PR TITLE
[Tests\Arithmetic] revising unit-tests

### PR DESCRIPTION
**Pull request by RickBarretto**
# Description

Since @drkameleon asked me to revise the unit-test and check if everything is ok here, I'm doing this PR.
He did an awesome work in #1077 and #1104 that fixed the most of the bugs and strange behaviors we had sometime ago found in #1072.

- Related (chronologic order)
  - #1072
  - #1077
  - #1104

## Type of change

- [x] Code cleanup
- [x] Add/Update unit-tests

### CODE REVIEW

**Comment by RickBarretto** [comment]
The setup failed 2 times... Strange.

**Comment by drkameleon** [comment]
> The setup failed 2 times... Strange.

I was about to write a comment about this...

I've been having the [exact same error in the other PR](Regarding the failing ). 😞 

As a matter of fact, I've been spending a good part of the past hour trying to figure out what is going on.

Perhaps it has to do with something, GitHub-related not working? But what baffles me the most is that the error seems to be trigger by the [nim-action](https://github.com/jiro4989/setup-nim-action):

Screenshot 2023-03-31 at 17 52 05

Nothing to do with us (I hope), but let's see how we can fix that 😉

**Comment by drkameleon** [comment]
P.S. The problem in my case is that I - finally! - want to merge, but until I see a totally green light from all CI action, I won't. So... waiting...

**Comment by RickBarretto** [comment]
Done! :wink:

**Comment by RickBarretto** [comment]
Done! 😉

**Review by drkameleon — APPROVED** [review]
Super nice job!!!

I mean... wow! That's so clean, so easy to read, so organized, *with* its comments. I simply love it!

Well done! 😉

**Comment by drkameleon** [comment]
Ready to merge! 🚀

**Pull request merged**
