### PR TITLE
Fix some builder bugs

### LINKED ISSUE #1313: Unrelated `uglify-js` message for developer, non-web builds
**Describe the bug**
When compiling the normal build, non-web, full mode, I'm getting an error message (that shouldn't supposedly be there at all).

```bash
uglifyjs: 3rd-party tool not available
```

**To Reproduce**

```bash
./build.nims build --who dev
```

**Expected behavior**

No error whatsoever. (no processing currently happening for normal, non-web builds)

**Screenshots**

Screenshot 2023-11-25 at 13 13 31

**Desktop (please complete the following information):**
 - OS: macOS

### PR DESCRIPTION
**Pull request by RickBarretto**
# Description

- [x] Fix default `--install` parameter:
  - Should install just when the user pass the `--install|-i` flag
- [x] Better error messages
  - Clear error messages should be shown to the user, even when not `--log`ging.
  - Fix message format: missing indentation
- [x] Fix workflow
  - Some workflows should be interrupted according to certain combinations of settings
  - [x] Fix: Running compression for non @web builds
  - [x] Fix: Running compression even with the `--raw` flag 
  - [x] Fix: Running installation for @web builds
  - [x] Fix: Running installation even without the `--install` flag

- Fixes #1313

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (implementation update, or general performance enhancements)

### CODE REVIEW

**Comment by RickBarretto** [comment]
It's giving "command not found", is it a CI error, have I done smt wrong?

**Comment by drkameleon** [comment]
Does it keep failing if you trigger a re-run of the CI?

**Comment by RickBarretto** [comment]
Strange... This broke three times. IDK the cause...

**Comment by drkameleon** [comment]
That's very weird... I cannot possibly see what could be wrong with macOS.

Let's see...

**Comment by drkameleon** [comment]
My hunch is it's something CI-related (apparently, it can't locate the binary?)

Here, afaik, it's building & running fine.

**Comment by RickBarretto** [comment]
Weird the amount of time taking these actions... (for MacOS and Windows)
Mac, for instance, is taking more than 7min to setup Nim...

**Comment by drkameleon** [comment]
> Comparing [Linux](https://github.com/arturo-lang/arturo/actions/runs/7203619731/workflow?pr=1332#L106-L109) with [MacOS](https://github.com/arturo-lang/arturo/actions/runs/7203619730/workflow?pr=1332#L72-L75) workflows:
> 
> ```
> # Mac, line 75:
> $ echo "$HOME/.arturo/bin" >> $GITHUB_PATH
> # Linux, line 108:
> $ echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
> ```
> 
> Hmmm, it seems to be the issue, isn't?
> 
> **Update:** No, this isn't.

That's super-weird. MacOS has never caused an issue with the CI builds... Perhaps it's not the workflow?
I'll build it here, wait 😉

**Comment by RickBarretto** [comment]
Hmmm... worked!
I'm passing the "./bin" to the `$GITHUB_PATH` now.

**Comment by drkameleon** [comment]
I've just built it here, using this exact PR and both modes (mini, full) worked fine - and the binaries are properly located in `/bin`.

I did it exactly like in the macOS-related workflow:

- `./build.nims build --mode mini --log`
- `./build.nims build --mode full --log`

**Comment by RickBarretto** [comment]
> and the binaries are properly located in /bin

So is this probably a CI/workflow error?

**Comment by RickBarretto** [comment]
Well... Review requested.

**Review by drkameleon — APPROVED** [review]
Looks perfectly fine. Plus, I actually built the thing on macOS and everything seems smooth (the weird warning about `uglify` eliminated too! 🚀 ).

Great job - again! 😉

**Comment by drkameleon** [comment]
And... 🥁 🥁 🥁 

Ready to merge! 🚀

**Pull request merged**
