### PR TITLE
[Collections\drop & take] fix SIGSEGV errors

### LINKED ISSUE #1190: [Collections\drop & take] returns SIGSEGV for some parameters
**Describe the bug**

> **Note**: I'm adding `take` to this issue too, because I think they are related functions... 

`drop` and `take` has some issues to be deal that returns `SIGSEVG`.
I'll care about their parameters as `collection`, the first one, and `number`, the second one.

## When `drop` fails
- When `number` is greater than `collection`'s length
  - ```red
    ; `take` implements this well, look:
    take [1 2 3] 4 ; => [1 2 3]
    drop [1 2 3] 4 ; timeout: sending signal KILL to command '/var/www/arturo-lang.io/arturo-0.9.83-safe-linux'
    ; should return `[]`
    ```
- When `number` is negative
  - ```red
    drop [1 2 3] neg 1 ; timeout: sending signal KILL to command '/var/www/arturo-lang.io/arturo-0.9.83-safe-linux'
    ; how should we handle this?
    ```

## When `take` fails
- When `collection` is a `:range` kind and `number` is greater than `collection`'s length
  - ```red
    ; `take` implements this well for other `collection`'s kind, look:
    take [1 2 3] 4 ; => [1 2 3]
    take 1..3 4 ; timeout: sending signal KILL to command '/var/www/arturo-lang.io/arturo-0.9.83-safe-linux'
    ; should return `[1 2 3]`
    ```
- When `collection` is a `:range` kind and `number` is 0
  - ```red
    ; `take` implements this well for other `collection`'s kind, look:
    take [1 2 3] 0 ; => []
    take 1..3 0 ; timeout: sending signal KILL to command '/var/www/arturo-lang.io/arturo-0.9.83-safe-linux'
    ; should return `[]`
    ```
- When `number` is negative
  - ```red
    take [1 2 3] neg 1 ; timeout: sending signal KILL to command '/var/www/arturo-lang.io/arturo-0.9.83-safe-linux'
    ; how should we handle this?
    ```

**Desktop (please complete the following information):**
 - version: `v/0.9.83 @ 2023-02-10T16:02:25+00:00`
 - arch: `x86_64/linux @safe`

**Additional context**

- [This message by Krenium at discord.com][discord]
- [This Playground's Code][playground]

[discord]: https://discord.com/channels/765519132186640445/829324913097048065/1111078465849004103
[playground]: https://arturo-lang.io/playground/?PhXdub#terminal

### PR DESCRIPTION
**Pull request by RickBarretto**
# Description

Fixes #1190

`drop` and `take` has some issues to be deal that returns `SIGSEVG`.
I'll care about their parameters as `collection`, the first one, and `number`, the second one.

How I handled these issues:

## When `drop` fails
- [x] When `number` is greater than `collection`'s length
  - ```red
    ; `take` implements this well, look:
    take [1 2 3] 4 ; => [1 2 3]
    drop [1 2 3] 4 ; => []
    ```
- [x] When `number` is negative
  - ```red
    drop [1 2 3] neg 1 ; timeout: sending signal KILL to command '/var/www/arturo-lang.io/arturo-0.9.83-safe-linux'
    ; how should we handle this?
    ```

## When `take` fails
- [x] When `collection` is a `:range` kind and `number` is greater than `collection`'s length
  - ```red
    ; `take` implements this well for other `collection`'s kind, look:
    take [1 2 3] 4 ; => [1 2 3]
    take 1..3 4 ; => [1 2 3]
    ```
- [x] When `collection` is a `:range` kind and `number` is 0
  - ```red
    ; `take` implements this well for other `collection`'s kind, look:
    take [1 2 3] 0 ; => []
    take 1..3 0 ; => []
    ```
- [x] When `number` is negative
  - ```red
    take [1 2 3] neg 1 ; timeout: sending signal KILL to command '/var/www/arturo-lang.io/arturo-0.9.83-safe-linux'
    ; how should we handle this?
    ```

## Type of change

- [x] Code cleanup
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Update documentation
- [x] Add/Update unit-tests

### CODE REVIEW

**Comment by drkameleon** [comment]
@RickBarretto Very good job here! 🚀 

Regarding negative numbers.... hmm... tricky... 🤔 

I guess I would go for one of the two following approaches:

- show an error and practically disallow negative numbers altogether
- work from the opposite direction when passing a negative number... in that case: `drop neg 10` would drop the last 10 elements (something like `take (size arr)-10`) and `take neg 10` would take the last 10 elements (something like `drop (size arr)-10`)

What do you think?

**Comment by RickBarretto** [comment]
@drkameleon as we can use numbers out of `collection`'s range without errors raised, I think that make negative numbers possible is the best approach to avoid big differences...
I'll implement this later.

Probably I won't be able to implement this today.

**Comment by RickBarretto** [comment]
@drkameleon, done! :rocket:

You can see how it's working in unit-tests. 😉

**Comment by RickBarretto** [comment]
BTW, I cleaned-up code and updated the documentation that was outdated, that was using the old `range` that returns an `:block` instead of `:range`...
I updated this too, and added the missing proper range example for `take`.

**Review by drkameleon — APPROVED** [review]
Awesome job @RickBarretto!! Very clean and thorough as usual!

P.S. I'll say it for N-th time, but it's a fact that I've been confirming every time I add/edit/remove anything in the library: your unit-tests rock! 🎸

**Comment by drkameleon** [comment]
Ready to merge! 🚀

**Pull request merged**
