### PR TITLE
Add Quantities' unit-tests

### PR DESCRIPTION
**Pull request by RickBarretto**
# Description

This unit-tests will cover the library Quantities and the Quantity type.

## Type of change

- [ ] Add/Update unit-tests

### CODE REVIEW

**Comment by drkameleon** [comment]
More related fixes: https://github.com/arturo-lang/arturo/pull/1231

But... there are still pending issues, e.g.: https://github.com/arturo-lang/arturo/issues/1232 😉

**Comment by RickBarretto** [comment]
> More related fixes: https://github.com/arturo-lang/arturo/pull/1231

@drkameleon, awesome!

**Comment by RickBarretto** [comment]
[Playing a bit with 4th dimension in Arturo, LOL][commit]...

[commit]: https://github.com/arturo-lang/arturo/pull/1209/commits/03f5be477ee2cf38695cf12608fd30c1b11f04e8

**Comment by RickBarretto** [comment]
Conversions are not working well for volume:

```red
    topic « volume - math // conversions
    
    ; Yes, almost everything went wrong here...
    ; ensure -> 1`gal   = 231`in3
    ; ensure -> 1`bbl   = 42`gal
    ; ensure -> 1`qt    = 1:4`gal
    ; ensure -> 1`p     = 1:2`qt
    ; ensure -> 1`cup   = 1:2`p
    ; ensure -> 1`floz  = 1:8`cup
    ; ensure -> 1`tbsp  = 1:2`floz
    ; ensure -> 1`tsp   = 1:3`tbsp
    ; ensure -> 1`bu    = 2150.42`in3
    ensure -> 1`cord    = 128`ft3
```

**Comment by RickBarretto** [comment]
Tested `'time` values...

**Comment by drkameleon** [comment]
> Conversions are not working well for volume:
> 
> ```red
>     topic « volume - math // conversions
>     
>     ; Yes, almost everything went wrong here...
>     ; ensure -> 1`gal   = 231`in3
>     ; ensure -> 1`bbl   = 42`gal
>     ; ensure -> 1`qt    = 1:4`gal
>     ; ensure -> 1`p     = 1:2`qt
>     ; ensure -> 1`cup   = 1:2`p
>     ; ensure -> 1`floz  = 1:8`cup
>     ; ensure -> 1`tbsp  = 1:2`floz
>     ; ensure -> 1`tsp   = 1:3`tbsp
>     ; ensure -> 1`bu    = 2150.42`in3
>     ensure -> 1`cord    = 128`ft3
> ```

That's very weird... I'll have to look into it... Noted! 😉

**Comment by RickBarretto** [comment]
A lot of issues with conversions... Everything that was defined as dependent from pounds, TBH.

```asm
    topic « mass - math // conversions

    ; A lot of conversions are actually broken, mainly when envolving lbs

    ensure -> equal? ~"|1`lb   --> `g |" ~"|45359237:100000`g|"
    ensure -> equal? ~"|1`slug --> `kg|" ~"|14.59390`kg|"
    ; Da is being considered as 0 when compared with kg, g or mg...
    ; ensure -> equal? ~"|1`Da   --> `kg|" ~"|1.66053906660e-27`kg|"
    ensure -> equal? ~"|1`gr   --> `mg|" ~"|64.79891`mg|"
    passed

    ; 1`oz is being considered as 135624986579`lb
    ; ensure -> 1`oz  =   1:16`lb
    ensure -> 1`ct  =   1:5`g
    ensure -> 1`t   =   1000`kg
    ; 1`ton is being considered as 542499946316000`lb
    ; ensure -> 1`ton =   2000`lb
    ; 1`lt is being considered as 607599939873920`lb
    ; ensure -> 1`lt  =   2240`lb
    ; 1`st is being considered as 3797499624212`lb
    ; ensure -> 1`st  =   14`lb
    ; 1`dwt is being considered as 300814707696`gr
    ; ensure -> 1`dwt =   24`gr
    ; 1`ozt is being considered as 1203258830784`dwt
    ; ensure -> 1`ozt =   20`dwt
    ; 1`lbt is being considered as 14439105969408`ozt
    ; ensure -> 1`lbt =   12`ozt
    passed
```

Look that the definition of `pound` is a bit problematic since we're having precision issues...

```nim
defUnit "lb",       "lb",       false,      "45359237:100000 g",        "pound", "pounds"
```

**Comment by RickBarretto** [comment]
I did a minor fix here: [[vm\values\quantities\definitinon]: minor fix](https://github.com/arturo-lang/arturo/pull/1209/commits/ae5de347e6ca7a3dee35886ebedcbfab890d0add)

**Comment by RickBarretto** [comment]
new issues found:
```red
$> 1`eV --> `J
=> 0 J
```

**Comment by drkameleon** [comment]
> new issues found:
> 
> ```red
> $> 1`eV --> `J
> => 0 J
> ```

This look like a precision error.

**Comment by RickBarretto** [comment]
Missing 19 units now!

**Comment by RickBarretto** [comment]
@drkameleon, finally finished!
I'll create a summary of bugs and errors I found, and then decide which of them are related to create the right issues to it. :wink:

**Comment by RickBarretto** [comment]
# Summary

## Precision issues
The choice for using rationals instead of floating points was to avoid precision loss.
But it is not being true here.

Example:
```red
$> 1`pm --> `nm
=> 4951760157141521/4951760157141521099596496896 nm
$> 4951760157141521/4951760157141521099596496896
=> 0
; But 1`pm --> `nm should return 0.001`nm instead
```

## Arithmetic error

I found it only once, but look:
```red
1`ang = (10 ^ (neg 10)) --> `m
SIGFPE: Arithmetic error.
```

## Division by Zero

For some reason the following code returns:

```red
1`Fr = 1`C
>> Runtime | uncaught system exception:
     error | division by zero
```

**Comment by drkameleon** [comment]
And... 🥁 🥁 🥁 

...ready to merge! 🚀

**Pull request merged**
