### PR TITLE
[VM/ast] Make "hanging" attributes work with pipes (`|`)

### LINKED ISSUE #1064: [VM/ast] verify attributes are correctly processed when using pipes
[VM/ast] verify attributes are correctly processed when using pipes

example:

```

1..10 | loop.with:'i 'x -> print [i x]

```

https://github.com/arturo-lang/arturo/blob/3f408e2ed98260b1972f8bd984af826bcb7a3174/src/vm/ast.nim#L592

```text
                target.addTerminal(baseNode)

    # TODO(VM/ast) verify attributes are correctly processed when using pipes
    #  example:
    #  ```
    #  1..10 | loop.with:'i 'x -> print [i x]
    #  ```
    #  labels: vm,ast,bug
    template addPotentialTrailingPipe(target: var Node): untyped =
        var added = false
        if i < nLen - 1:
ndex db507f495a..1d92eb984d 100644
++ b/src/vm/eval.nim
```

09c649c5cb58ce512ecf74ee06b0b0ee777b0e3b

### LINKED ISSUE #1103: Attributes not working at the end of pipe statements
**Describe the bug**

See: https://discord.com/channels/765519132186640445/829324913097048065/1088867145980592309

Also related: #1064

### PR DESCRIPTION
**Pull request by drkameleon**
# Description

We have to make sure that "hanging" attributes (= without a trailing parameter) in `|` constructs work fine.

### Example

**This:**

```red
print split.every:3 "abcde fghijklmnop qrstuvwxyz"
```

**Should be identical to:**

```red
"abcdefghijklmnopqrstuvwxyz" | split.every:3 | print
```

### The issue

In the above example, the first piece of code results in this bytecode:

```
        ================================
         DATA
        ================================
        0: abcde fghijklmnop qrstuvwxyz :string
        1: every :attributelabel

        ================================
         CODE
        ================================
        push0
        consti3
        attr1
        split
        print
        end
```
which is perfectly correct.

While the second one generates:

```
        ================================
         DATA
        ================================
        0: abcdefghijklmnopqrstuvwxyz :string
        1: every :attributelabel

        ================================
         CODE
        ================================
        push0
        split
        consti3
        attr1
        print
        end
```

(basically, the `.every:3` part is grouped with `print` and *not* with `split` ❗ )

-----

Fixes #1064 
Fixes #1103 

## Type of change

- [x] Code cleanup
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by RickBarretto** [comment]
I'll be looking how it's going on to learn how to deal with these kind of issues...

**Comment by drkameleon** [comment]
> I'll be looking how it's going on to learn how to deal with these kind of issues...

To be perfectly honest, I don't even have any idea how this is going to be solved! Like... honestly! 🤣 haha

The AST code is one of those cases where while I was working on the code, for days in a row, it made perfect sense. Now, part of it *still* makes sense, but the other half looks like perfect swahili... (The pipes implementation concretely is *extremely* complicated in logic, to even explain what we're doing with words...) So, I'll have to carefully see it step by step for myself!

That being said, I have a feeling the "fix" may be just 1-2 lines. The problem is... when I'll be able to spot it!

**Comment by drkameleon** [comment]
@RickBarretto You've turned me into a unit-testing addict: https://github.com/arturo-lang/arturo/blob/d7fcd3fc05676903595f67a581b1770ade89f4fd/tests/unittests/pipes.art 🤣

**Comment by drkameleon** [comment]
Ready to merge! 🚀

**Pull request merged**
