### PR TITLE
Fix custom types example

### PR DESCRIPTION
**Pull request by Eloitor**
# Description

Fix custom types example.

I'm not sure about the comparator, since deleting that line doesn't change anything.

## Type of change

- [ ] Code cleanup
- [ ] Unit tests (added or updated unit-tests)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (implementation update, or general performance enhancements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation (documentation-related additions)

### CODE REVIEW

**Comment by drkameleon** [comment]
Good idea - we should start dealing with pending documentation issues asap!

Re: comparator.

Right now, comparing object of a given user-defined type is meant to happen either implicitly or using a provided `compare:` magic method.

Now, that magic method, we may define it ourselves (e.g. `compare: method [that][ compare \x that\x ]`, etc), or if it's just about one specific field, we could use the `sortable` helper, like: 
```
compare: sortable 'age
```

And it most definitely influence the output. 🤔 
Have you tried sorting by... a different field?

**Comment by Eloitor** [comment]
What does it do if no sortable method is defined?

**Comment by drkameleon** [comment]
> What does it do if no sortable method is defined?

The answer to the mystery:

https://github.com/arturo-lang/arturo/blob/master/src/vm/values/comparison.nim#L348-L356

So, if you did:

```
customObjectA < customObjectB
```

it would:

- first look if there is a `compare` magic method defined
- then look for `less?`
- and if none of that is defined, it would return `false` (however, `customObjectB < customObjectA` would *also* return false)

**Comment by drkameleon** [comment]
Another example:

Screenshot 2024-10-09 at 14 22 54

**Comment by Eloitor** [comment]
Oh... `# should throw!` ... I agree...

**Review by drkameleon — APPROVED** [review]

**Comment by drkameleon** [comment]
Ready to merge! 🚀

**Pull request merged**
