### PR TITLE
[Net\request] add String support for *body*

### LINKED ISSUE #1790: [Net\request] Feature Request: support :string body
`request` should support passing raw strings for `body`, thus enabling the same behavior as `curl -X POST -d a=b&c=d`—simply that the url-encoded query string is now in the body instead of the url.

I've found an api that requires this instead of multipart form data, so that's why it's occurring to me to request this feature.

### PR DESCRIPTION
**Pull request by drkameleon**
# Description

Fixes #1790 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by drkameleon** [comment]
@nick-chandoke Can you please have a look? (all the relevant binaries are in the buids above, I can point you to them directly if you have any issue)

Also, if you can, it would really help if you could give me some concrete example so that we can make sure it's working 😉

**Comment by nick-chandoke** [comment]
Hi, sorry for being away awhile! The only real-world example that I know of requires authentication with a server, so it cannot serve as a test case. However, it's effectively the same as testing that `request.post "http://localhost:8080" "x=ftp://site.com&y=./"` is the same (up to request headers) as `curl -X POST http://localhost:8080 -d 'x=ftp://site.com&y=./'`.

Indeed, viewing & comparing the requests as plaintext by running `netcat -l -p 8080`, I have verified are in fact equal as they should be! Very cool!

**Comment by drkameleon** [comment]
> Hi, sorry for being away awhile! The only real-world example that I know of requires authentication with a server, so it cannot serve as a test case. However, it's effectively the same as testing that `request.post "http://localhost:8080" "x=ftp://site.com&y=./"` is the same (up to request headers) as `curl -X POST http://localhost:8080 -d 'x=ftp://site.com&y=./'`.
> 
> Indeed, viewing & comparing the requests as plaintext by running `netcat -l -p 8080`, I have verified are in fact equal as they should be! Very cool!

Thanks a lot for the feedback! Really appreciated! 😉 

I'm working on a - slightly-related - (sub)PR and I will merge them both as soon as we get it all solved (not too long from now, hopefully!)

**Comment by drkameleon** [comment]
And... 🥁 ...

...ready to merge! 🚀

**Pull request merged**
