### PR TITLE
Make the whole project documentable

### PR DESCRIPTION
**Pull request by drkameleon**
# Description

Since there isn't much info for developers (not for the usage of Arturo, but for its internal), making use of Nim's built-in docgen tool wouldn't be a bad idea.

Plus, it will add something useful to the project, whether related to Nim's tool or not.

The resulting Developer documentation will go here: https://arturo-lang.github.io/dev-docs/

## Type of change

- [x] Code cleanup
- [x] This change requires a documentation update

### CODE REVIEW

**Comment by celtic-coder** [comment]
Hi Yanis (@drkameleon),

The https://arturo-lang.github.io/dev-docs/extras/miniz.html page seems to have an extra line at the top:

`define tinfl_init(r) do { (r)->m_state = 0; } MZ_MACRO_END `

Is this expected?

Kind Regards,
Liam

**Comment by drkameleon** [comment]
> Hi Yanis (@drkameleon),
> 
> The https://arturo-lang.github.io/dev-docs/extras/miniz.html page seems to have an extra line at the top:
> 
> `define tinfl_init(r) do { (r)->m_state = 0; } MZ_MACRO_END `
> 
> Is this expected?
> 
> Kind Regards, Liam

Liam, Hi! :)

Thanks for letting me know!

The truth is there are many... extra things everywhere! I don't think I'll manage to clean them up soon enough! haha

In any case, thanks to @RickBarretto who mentioned the need for some "real" Developer documentation (and contributing toward this end himself), I finally got the idea to actually go for it and - potentially - make use of Nim's tool.

Obviously, there's a lot of way to go, but it's a start still! :)

**Comment by RickBarretto** [comment]
> Hi Yanis (@drkameleon),
> 
> The https://arturo-lang.github.io/dev-docs/extras/miniz.html page seems to have an extra line at the top:
> 
> `define tinfl_init(r) do { (r)->m_state = 0; } MZ_MACRO_END `
> 
> Is this expected?
> 
> Kind Regards, Liam

You are right! This isn't expected. It should be just a comment, and not part of documentation.
This happens, because commentaries are initialized with a `#` and documentation are initialized  with a `##` in Nim.
Good job! If you find more, please, let us know!

I did a PR #778, that fixes it!  🚀

**Comment by drkameleon** [comment]
A lot of work has been done here... 😄 

Obviously, the objective here for me is not document the whole universe in one shot but to set the foundations so that the whole project may - at some point - be properly documented from a developer's perspective. That being said, I'm more than super-satisfied with the progress; and I'll obviously continue adding things here and there, only one bit at a time.

But for now, I think it would be more practical if I re-focused on things that matter more.

So...

Ready to merge! 🚀

**Pull request merged**
