### PR TITLE
Lib collections unittest improvements

### LINKED ISSUE #157: [Helpers\arrays] verify/debug implementation for flattened
[Helpers\arrays] verify/debug implementation for flattened

https://github.com/arturo-lang/arturo/blob/6a2111084a957c7dd644e19bb29af74e170c2ce5/src/helpers/arrays.nim#L21

```text
#=======================================

# TODO(Helpers\arrays) verify/debug implementation for flattened
#  labels: library, helpers, bug
proc flattened*(v: Value,once = false,level = 0): Value =
    result = newBlock()

    for item in v.a:
        if item.kind==Block and ((not once) or (once and level==0)):
            for subitem in flattened(item,once,level+1).a:
                result.a.add(subitem)
        else:
            result.a.add(item)
ndex 74324c22..500f4914 100644
++ b/src/library/Collections.nim
```

caf15697ad274d58a7feb6d8b919dade11f8d8ba

### PR DESCRIPTION
**Pull request by RickBarretto**
# Description

Adding better coverage to bugs and another things.
Notes were and will be added to this unit-test when bugs were found.

The last time, I used [Collection's Documentation](https://arturo-lang.io/documentation/library/collections/) as base for my tests. This time, I'm using the [source code from current master](https://github.com/arturo-lang/arturo/blob/60d5d0d85cfc1b6eaadbac5a8b3902daffe1df8a/src/library/Collections.nim).

Fixes #157 

> ### [Issues found](https://github.com/arturo-lang/arturo/pull/910#issuecomment-1360529146)

## Type of change

- [x] Update/Add unit-tests

### CODE REVIEW

**Comment by RickBarretto** [comment]
It's even in progress.
So, I will do more tests for "bugs" that I found. Then open new Issues, and replace the comments in code by a reference for the right Issue.
Also, I'm using the latest version from `master`.
And, I'll clean this code too. 🙂

**Comment by RickBarretto** [comment]
## Issues Opened
Make sure to cover this issues on unit-tests when solved.
- [ ] #911
  - [ ] covered?
- [ ] #912
  - [ ] covered?

**Comment by RickBarretto** [comment]
Alright! SOrry for the amount of issues and commits, but I discovered much things broken with these unit-tests. 🙂

**Comment by drkameleon** [comment]
Awesome job! Great stuff, really! 😄 

And... don't worry about the number of issues you found; it's quite the opposite actually: the more you spot, the better for the language! 

Especially the Collections module: a) is an important one, b) the way Arturo has been developed, this particular module has become kind of a patchwork, so there is a higher chance you may find things... (there are other that have been tested thoroughly - e.g. Iterators - but even then I wouldn't be suprised if there were bugs).

As [Matz](https://en.wikipedia.org/wiki/Yukihiro_Matsumoto) put it in an interview I watched, programming is *not* about creating a "perfect" thing from day one, but adding things gradually so that you head towards this result. 😉

**Comment by RickBarretto** [comment]
> And... don't worry about the number of issues you found

Alright 😉! I really think that the philosophy of **fail fast** is a good approach. So, is better fail now than after. A good talk about it is the [Failure is Always an Option - Dylan Beattie - NDC London 2022](https://invidious.snopyta.org/watch?v=Av3QP940L2c) [[youtube](https://www.youtube.com/watch?v=Av3QP940L2c)]

So, let's go!

> the way Arturo has been developed, this particular module has become kind of a patchwork, so there is a higher chance you may find things... 

Alright!

---
Also, [@matz](https://github.com/matz) is a great programmer, I heard about him from [@akitaonrails](https://github.com/akitaonrails) (my favorite YouTuber and programmer from Brazil, and also he was the organizer of RubyConf on Brazil). Matz has a lot of knowledge and I love the Artima's interview with him 🙂. For some reason, the [first interview](https://www.artima.com/intv/ruby1.html) is returning a 404 error, but you can find it [translated to portuguese on AkitaOnRails Blog](https://www.akitaonrails.com/2006/10/09/entrevista-com-yukihiro-matsumoto-parte-i).

**Comment by RickBarretto** [comment]
Alright, Its missing just some types testing for some functions. 🚀
But I think that new issues shouldn't appear.

**Comment by RickBarretto** [comment]
@drkameleon, I finished this!
So, now the adventure will be fix all issues, and add unit-test to them.
Also, some parts I can't resolve, things as `:bytecode`, some `:binary` operations, `:store` and `:object`.
I added a tag called `todo` to know where is these parts. But, I don't know how to test them properly.

**Comment by drkameleon** [comment]
> @drkameleon, I finished this! So, now the adventure will be fix all issues, and add unit-test to them. Also, some parts I can't resolve, things as `:bytecode`, some `:binary` operations, `:store` and `:object`. I added a tag called `todo` to know where is these parts. But, I don't know how to test them properly.

Very good job, obviously! 😄 

As you've noticed, I have already started solving whatever I can, one by one. And hopefully, it won't take long before I manage to sort them out.

Re: `:store` & `:object`, both not properly documented (the former being a very, very recent additions), think of them like Dictionaries.


**Stores** 

To create a Store, all you have to do is:

```red
mystore: store.auto "somename"

mystore\name: "John"
mystore\surname: "Doe"
```

so... it looks like a normal Dictionary. The catch is: *everything* is automatically saved to disk. And if you open the store again, the data is automatically there, loaded from disk. This is a pretty awesome feature tbh. Right now, it supports "native stores" (data stored as Arturo data), JSON & SQLite. But the sky's the limit - we could make this fly... 😉 

**Objects**

```red
; we define a new type, with two fields - think of it like a very-specific type of dictionary
; and let's forget for now what this second parameter is for
define :person [name,surname][]

; now let's create a new person
personA: to :person ["John" "Doe"]

; and let's print, let's say it's name
print personA\name     ; => will print "John"

; of course we can check whether a variable is of that type
is? :person personA     ; => will return "true"
```

But in general, think of them like Dictionaries on steroids... both Stores and Objects 😉

**Comment by celtic-coder** [comment]
> Make sure to cover this issues on unit-tests when solved.

Great work on [this list](https://github.com/arturo-lang/arturo/pull/910#issuecomment-1360529146)! 👍

**Comment by RickBarretto** [comment]
Thank you, @celtic-coder!!!! :heart: 
And, also, brilliant idea with this store, @drkameleon! 
I'll try to add unit-tests for them.

**Comment by RickBarretto** [comment]
Branch updated!

**Comment by RickBarretto** [comment]
@drkameleon I updated arturo from main branch, look what is happening:
When I run the `lib.collections.art`
image
It's breaking on some part of this code
image

When I try to invoke Arturo
image

**Comment by RickBarretto** [comment]
Btw, more 10 unit-tests covered! 🚀

**Comment by RickBarretto** [comment]
Alright! Everything I could do, I done!
@drkameleon. If you want to merge! Go on!
- I added every issue that I covered on unit-tests [here](https://github.com/arturo-lang/arturo/pull/910#issuecomment-1360529146).
- There is a conflict because I updated this branch from main
- I'll add some new issues, since Arturo is breaking when invoked, and `split.path` is breaking too.

**Comment by RickBarretto** [comment]
## Update!
Building from `master`:
image
It's working well, maybe it can be this merge conflict that was breaking. I'll test it for `split.path` too.

**Comment by RickBarretto** [comment]
Alright! I think it's read to merge!
All conflicts were fixed, I completed everything I could and CI is working.

> Note: I didn't tested for `:bytecode` and `:store`. Since I don't know how to test bytecode properly, and store is on early development.

**Comment by drkameleon** [comment]
I've *finally* managed to spot what was going on with the Range values!

Apparently, the whole problem stems from these lines:

https://github.com/arturo-lang/arturo/blob/ea1ac567c97bfeddd2ddb4ddd020340775258d4b/tests/unittests/lib.collections.art#L211-L213

In a few words, you redefine `range` (and thus the effect of `..`) and given that `do` blocks are not scoped anymore (we may add another function that does create scoped blocks, e.g. `scoped [ ]`), the change propagates everywhere... 😉 

Phew... This is quite a relief because I started debugging the generated bytecode to see what was going on and I was afraid it could be something even deeper.

Let's see... I'll try to fix the pending conflict, and perform all necessary changes so that the PR is ready!

Good job, again! 😄

**Comment by drkameleon** [comment]
Hmm... I guess I'll take a break (apparently after updating my macOS, the whole Xcode toolchain had to be updated as well, meaning... I was left even without Git (!)... lol)

That being said, I think we're pretty much good to go - I'll fix the remaining issues (so that CI doesn't fail) and cleanup a bit the code. But other than that, I believe on Monday the PR will be merged! 😉

**Comment by drkameleon** [comment]
So, I've fixed a couple of things; re-added some unit-tests where the underlying bugs have been fixed and performed a general cleanup.

Leaving aside the issue with `sort` and Dictionary values (which seems a tiny bit more complicated and I don't want to make a mess out of it - I'll solve it in another PR along with the corresponding tests), I think it's time to consider this PR complete.

Great work in general ❗❗❗ (I'm looking forward to more similar ones! 😉  Creating new issues is the best way to discover hidden things that may not be working as they're supposed to! I'll also create some new TODOs based on things I discovered while going through all of your unit-tests one by one. Awesome stuff!)

-----

That being said...

... ready to merge! 🚀

**Comment by RickBarretto** [comment]
Awesome work, @drkameleon! 🚀 🙂

**Pull request merged**
