### PR TITLE
Cleanup VRational implementation

### PR DESCRIPTION
**Pull request by drkameleon**
# Description

...

## Type of change

- [x] Code cleanup

### CODE REVIEW

**Comment by drkameleon** [comment]
@RickBarretto Apparently, I have managed to fix [this](https://github.com/arturo-lang/arturo/issues/1131) as well, exactly as you suggested (and yes, in the end I think you were 100% right). It might not be the most common thing one would do, but on the other hand... "why not?!" 😉 

**How it works as per this PR** (along with some showcase of the new literal-Rational syntax 😄 ):

Screenshot 2023-04-28 at 09 58 12

**Comment by drkameleon** [comment]
Ready to merge! 🚀

**Comment by RickBarretto** [comment]
> @RickBarretto Apparently, I have managed to fix this as well, exactly as you suggested (and yes, in the end I think you were 100% right).

Wow, thanks a lot!

I have some questions, is this a new thing?

```red
1:2 * 3:4
```

It's much better than use `to :rational`, and more, as `:` is already used for other things and there is no specific function to rational (we use `to` instead) I think it's evaluated at parsing time, what means that `[1:3]` is parsed as a `[:rational]` without the need of use `array` function like this `@[1:3]` to recognize the internal value as a `:rational`, I may be wrong because I didn't test it yet, but it looks good to me.

You know, if `:` is an alias to a function it will not be evaluated at parsing-time, and will return:

```red
inspect [3:2]
; [ :block
;     2 :integer
;     : :symbol
;     3 :integer
; ]
```

Anyway, even if `[1:3]` isn't the same as `[:rational]` it's good enough to me too. 🙂

**Comment by drkameleon** [comment]
Also, so that you can appreciate the changes a bit, since Rational numbers in Arturo can now handle infinitely large (or small) ratios, this is also possible:

Screenshot 2023-04-28 at 16 41 03

(In the previous version, you'd get either 0, or something totally random; and... wrong)

**Pull request merged**
