### PR TITLE
Feature 867 add times attribute to chop function

### LINKED ISSUE #867: [Collections/chop] add `.times` option to remove multiple items
[Collections/chop] add `.times` option to remove multiple items

Also, times should accepts literals too

https://github.com/arturo-lang/arturo/blob/1136d74ff6685ec5b16c64021b3cf1a0dfc45fa8/src/library/Collections.nim#L117

```text
                        push newBlock(cleanAppend(x, y, singleValue=true))

    # TODO(Collections/chop) add `.times` option to remove multiple items
    #  Also, times should accepts literals too
    #  labels: library, new feature
    
    builtin "chop",
        alias       = unaliased,
        rule        = PrefixPrecedence,
```

2b5dce71bfc9d5f39816cf8b4de85f8242ce42f2

### PR DESCRIPTION
**Pull request by RickBarretto**
# Description

Adds `.times` feature to `chop` function.
Usage: `chop.times: 3 "Arturo" ; => "Art"`

Fixes #867

It will require updates on documentation, build number and unit-test output's file

Running on my local build:
testing new feature on my local build

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Updates unit-tests
- [x] Updates examples  
- [ ] This change requires a documentation update
- [ ] This change requires a new build
- [ ] This change requires an update on `lib.collections.res` file

### CODE REVIEW

**Comment by RickBarretto** [comment]
It may break because I didn't updated the `lib.collections.res` file, just `lib.collections.art`, since I don't know how to it properly.

**Review by drkameleon — APPROVED** [review]
Awesome job, again! :)

P.S. You're officially the no.2 contributor to Arturo, but number of contributions...

**Comment by drkameleon** [comment]
I hope it's fixed. 🤔 

And yes, I can confirm #872 is a real issue on Windows... :S

**Comment by drkameleon** [comment]
Ready to merge! 🚀

**Comment by RickBarretto** [comment]
> P.S. You're officially the no.2 contributor to Arturo, by number of contributions... 🚀

I'm happy to help you! 🚀

**Pull request merged**
