### PR TITLE
[Collections\get]: add complex numbers fields support

### PR DESCRIPTION
**Pull request by RickBarretto**
# Description

This PR adds get's support to complex numbers, making its fields accessible using dictionary or array notation... 

## Type of change
- [x] Unit tests (added or updated unit-tests)
- [x] Enhancement (implementation update, or general performance enhancements)
- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation (documentation-related additions)

### CODE REVIEW

**Comment by RickBarretto** [comment]
Done! 🚀😉

**Comment by drkameleon** [comment]
Wow! Really impressed! 😄 🚀 

Well done!

P.S. And, no, I don't think the change was "easy"; unless you totally know what you're doing... 😉

**Comment by drkameleon** [comment]
Ready to merge! 🚀

**Comment by RickBarretto** [comment]
> P.S. And, no, I don't think the change was "easy"; unless you totally know what you're doing... 😉

🙂 Thanks!

Side note: My VSCode removed the extra-lines on unit-tests, so in the end it send a high diff, my bad about that! I had not noticed.

**Comment by drkameleon** [comment]
> Side note: My VSCode removed the extra-lines on unit-tests, so in the end it send a high diff, my bad about that! I had not noticed.

Don't worry! 😉

**Pull request merged**
