### PR TITLE
Re-implement Quantity values

### PR DESCRIPTION
**Pull request by drkameleon**
# Description

Quantity values - albeit a relatively new feature in Arturo - is a rather interesting feature, that could potentially give the language an edge and allow its use in different sectors (e.g. scientific calculations, engineering, etc).

That being said, there are already a few pending issues (mostly regarding the operations between different quantities/etc), which is anything but bulletproof (at least so far).

### The goals of this PR:
(*that I've been preparing for at least the past 2 weeks, [writing and re-writing and re-writing](https://github.com/arturo-lang/arturo/pull/1141))

- Re-implement the Quantity value type from scratch
- Add better core unit support
- Make quantities and units [Dimension-aware](https://en.wikipedia.org/wiki/Dimensional_analysis)
- Allow for more complex unit expression (with compound units, etc)
- Make operation rules less rigid when we don't have to be too strict, and make them stricter in case the operation shouldn't be allowed

### Stretch goal

- Allow the user to optionally define his own units

### Other changes

(*Most of them directly derived from the above - or at least very relevant)

- Rational values now support GMP BigNum's (in a few words: in non-MINI builds, they can now represent "infinitely" large or small numbers 🚀 ; also see: #1004)
- The Quantity literal definition will be using [backticks instead of colons](https://github.com/arturo-lang/arturo/pull/1175) (e.g. ``2`m`` instead of `2:m`) **❗ Experimental**
- Introduced [literal syntax for Rational](https://github.com/arturo-lang/arturo/pull/1174) values (e.g. `2:3`) 
- Changed syntax for Char literals to use single ticks (e.g. `'a'`) **❗ Experimental**

------

💬  **Discussion:** @ https://github.com/arturo-lang/arturo/discussions/1144

👀  **Also see:** [1](https://discord.com/channels/765519132186640445/829324913097048065/1097888968021921843), [2](https://discord.com/channels/765519132186640445/829324913097048065/1098166418626846761) & [3](https://discord.com/channels/765519132186640445/829324913097048065/1098168376494403635)

------

## Fixes

Fixes: #1004 
Fixes: #1110 
Fixes: #1131 

## Type of change

- [x] Code cleanup
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### CODE REVIEW

**Comment by celtic-coder** [comment]
> @RickBarretto I keep testing and testing (and testing...) and I'm at the stage where I keep hitting unit-test issues. I cannot imagine what would have happened if you hadn't done it so thoroughly (especially the Arithmetics-related tests). Pure awesomeness! 😉

In a galaxy far, far away, I once worked for a major software company, where the team of which I was a part, supported over 20k developers. It was our job to keep the servers and the software that they used on a daily basis, in smooth running order. You can't imagine the amount of testing that went on. And despite all of this, there were still bugs! 😢 

As a former database developer, I am a huge fan of unit tests. And in my own case, I used to unit-test the unit-tests! (Well, almost!). Developing software of any kind requires certain specific skills. Writing good tests requires an allied list of skills, which, unfortunately, are in short supply.

So, as @drkameleon has said: great work @RickBarretto!

**Comment by RickBarretto** [comment]
> I cannot imagine what would have happened if you hadn't done it so thoroughly (especially the Arithmetics-related tests). Pure awesomeness! 😉

Appreciated! 🙂 

> I once worked for a major software company, where the team of which I was a part, supported over 20k developers

@celtic-coder, WOW! I can imagine this! 
Unit tests are really important for software development, you spend some hours to implement them, but it can save thousands and thousands of hours to solve new bugs that had already been solved. I have an idea that there is more of this in your area, database management is a crucial area that can spend not only working hours to solve problems, but also money. If you lose or  corrupt some customer's data, the company will lose (a lot of, sometimes) money.

**Comment by drkameleon** [comment]
First quasi-building version! 🎉  (There must be tons of stuff to be fixed & there are a couple of case where I simply commented-out code to make it go forward, since the updated implementations would probably take some time, but we're definitely getting there - slowly but... surely!)

**Comment by RickBarretto** [comment]
👀👀👀

It's not a draft anymore and all checks have passed...
Excited for this PR! 🔥

**Comment by drkameleon** [comment]
> 👀👀👀
> 
> It's not a draft anymore and all checks have passed... Excited for this PR! 🔥

Totally accurate!

It took me some time to revise everything and - at least - make it compile but we're definitely getting closer! :)

Now, I'll have to double-check everything, clean up any leftovers, write some tests and we're quite ready to go! 🚀

**Comment by drkameleon** [comment]
So... after close to 2 months, as we were saying with @RickBarretto, I think it's time to finally merge this to the main branch, so that we can work on it, step-by-step, and on a per-issue basis, rather than keep bloating this PR again and again, until it becomes an unmanageable mess. (Is it 100% perfect? It's not. But then, nothing is...)

And, of course, I'll take the time to open as many issues as possible so that we can start ironing things out. 😉 

That being said...

🥁 🥁 🥁 

...ready to merge! 🚀

**Comment by RickBarretto** [comment]
Awesome work! @drkameleon .
These PR's features already is one of my favorites.

I had the chance to play with that before the merge, as you ask me for it. And... Everything is fan-tas-tic! 

Now, let's get things happen and see how it will behavior with the time.

Again, awesome work as always!

**Pull request merged**
