### PR TITLE
[Collections] add `.deep` attribute for `contains?` & `in?`

### LINKED ISSUE #958: [Collections/in?] add new `.deep` option?
[Collections/in?] add new `.deep` option?

same as with `contains?`

https://github.com/arturo-lang/arturo/blob/d4b01ddb18a43062134a1ff23f9fe41366d97055/src/library/Collections.nim#L642

```text
                else: discard

    # TODO(Collections/in?) add new `.deep` option?
    #  same as with `contains?`
    #  labels: library, enhancement, open discussion

    # TODO(Collections/in) add new `.key` option?
    #  same as with `contains?`
    #  labels: library, enhancement, open discussion
    builtin "in?",
        alias       = unaliased,
        rule        = PrefixPrecedence,
```

1f4fee773fb70bfe94b7d9e1d390fc32bcf12373

### PR DESCRIPTION
**Pull request by RickBarretto**
# Description
`contains?.deep` and `in?.deep` should search recursively for some value in a container (`:block` or `:dictionary`) and return a `:logic`.

Fixes #958 #955 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Update unit-tests
- [x] This change requires a documentation update
- [x] Add usage

### CODE REVIEW

**Comment by RickBarretto** [comment]
It'll break for dictionaries, since `toSeq(x.d.values)` don't get values in deep...

**Comment by RickBarretto** [comment]
I'm creating a custom function to it. :wink:

**Comment by RickBarretto** [comment]
Done! 😉

**Review by drkameleon — APPROVED** [review]
Super nice! You're a machine! 😄

**Pull request merged**
