### PR TITLE
Add `:pathLiteral` support to Libraries

### LINKED ISSUE #1450: [Bitwise\shl] add support for PathLiteral values
[Bitwise\shl] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Bitwise.nim#L149

```text
            generateOperationB("or", `||`, `||=`)

    # TODO(Bitwise\shl) add support for PathLiteral values
    #  labels: library, enhancement
    builtin "shl",
        alias       = unaliased, 
        op          = opShl,
```

7fa49814bacc298eaf074a1b7b56c92cb966cfc8

### LINKED ISSUE #1451: [Collections\append] add support for PathLiteral values
[Collections\append] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Collections.nim#L60

```text
    #----------------------------

    # TODO(Collections\append) add support for PathLiteral values
    #  labels: library, enhancement
    builtin "append",
        alias       = doubleplus,
        op          = opAppend,
```

4209ec5fd7cb6bcfbdcbf092fbb453b5d9551748

### LINKED ISSUE #1452: [Collections\chop] add support for PathLiteral values
[Collections\chop] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Collections.nim#L231

```text
                        push(newBlock(@[x]))

    # TODO(Collections\chop) add support for PathLiteral values
    #  labels: library, enhancement, easy
    builtin "chop",
        alias       = unaliased,
        op          = opNop,
```

188c73df5bf4dde9c780f240214f07c6bc445200

### LINKED ISSUE #1453: [Collections\decouple] add support for PathLiteral values
[Collections\decouple] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Collections.nim#L375

```text
            push(newBlock(zip(x.a, y.a).map((z)=>newBlock(@[z[0], z[1]]))))

    # TODO(Collections\decouple) add support for PathLiteral values
    #  labels: library, enhancement, easy
    builtin "decouple",
        alias       = unaliased,
        op          = opNop,
```

bdc61a8dbf36c8e2654d73e8930a4005231c5574

### LINKED ISSUE #1454: [Collections\drop] add support for PathLiteral values
[Collections\drop] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Collections.nim#L481

```text
            push(newDictionary(dict))

    # TODO(Collections\drop) add support for PathLiteral values
    #  labels: library, enhancement, easy
    builtin "drop",
        alias       = unaliased,
        op          = opNop,
```

3bc6816ff13c091ca05be2165b3d1593e99b8ebf

### LINKED ISSUE #1455: [Collections\empty] add support for PathLiteral values
[Collections\empty] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Collections.nim#L556

```text
                else: discard

    # TODO(Collections\empty) add support for PathLiteral values
    #  labels: library, enhancement, easy
    builtin "empty",
        alias       = unaliased,
        op          = opNop,
```

c1b157a45bb3501459bea2b26d724fe1b2de4633

### LINKED ISSUE #1456: [Collections\extend] add support for PathLiteral values
[Collections\extend] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Collections.nim#L583

```text
                else: discard

    # TODO(Collections\extend) add support for PathLiteral values
    #  labels: library, enhancement, easy
    builtin "extend",
        alias       = unaliased,
        op          = opNop,
```

03a901410d67b0b4bf8a8bb70e41d3c8b994503d

### LINKED ISSUE #1457: [Collections\flatten] add support for PathLiteral values
[Collections\flatten] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Collections.nim#L655

```text
                    else: push(x.a[0])

    # TODO(Collections\flatten) add support for PathLiteral values
    #  labels: library, enhancement
    builtin "flatten",
        alias       = unaliased,
        op          = opNop,
```

8607d5b5bb944e7c143b18c1c24a255544777053

### LINKED ISSUE #1458: [Collections\insert] add support for PathLiteral values
[Collections\insert] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Collections.nim#L914

```text
    #  `insert.many [1 4 5 6] 1 [2 3]` and get back `[1 2 3 4 5 6]`
    #  labels: library, enhancement, open discussion 

    # TODO(Collections\insert) add support for PathLiteral values
    #  labels: library, enhancement, easy
    builtin "insert",
        alias       = unaliased,
        op          = opNop,
```

b14129f0a10210d85f965f7195f42f44b279e66e

### LINKED ISSUE #1459: [Collections\pop] add support for PathLiteral values
[Collections\pop] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Collections.nim#L1219

```text
                push(newBlock(getPermutations(x.a, sz, doRepeat).map((
                        z)=>newBlock(z))))

    # TODO(Collections\pop) add support for PathLiteral values
    #  labels: library, enhancement, easy
    builtin "pop",
        alias       = unaliased,
        op          = opNop,
```

fdab50a5149d7770dd8c4ad8ed90f6c3c30fb9a4

### LINKED ISSUE #1460: [Collections\prepend] add support for PathLiteral values
[Collections\prepend] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Collections.nim#L1301

```text
            else: raise newException(ValueError, "Attribute 'n can't be 0 or negative.")
                
    # TODO(Collections\prepend) add support for PathLiteral values
    #  labels: library, enhancement
    builtin "prepend",
        alias       = unaliased,
        op          = opNop,
```

93cf37381316acb1e5166380011e4cbd2fdea329

### LINKED ISSUE #1461: [Collections\remove] add support for PathLiteral values
[Collections\remove] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Collections.nim#L1424

```text
    #  Example: `remove.index 3 'a, debug a`
    #  labels: library, bug

    # TODO(Collections\remove) add support for PathLiteral values
    #  labels: library, enhancement
    builtin "remove",
        alias       = doubleminus,
        op          = opNop,
```

5019d2b418cfe2409c4f95e3d788317600ea22f5

### LINKED ISSUE #1462: [Collections\repeat] add support for PathLiteral values
[Collections\repeat] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Collections.nim#L1557

```text
                            push(newObject(x.proto, x.o.removeAll(y, key), x.magic))

    # TODO(Collections\repeat) add support for PathLiteral values
    #  labels: library, enhancement
    builtin "repeat",
        alias       = unaliased,
        op          = opNop,
```

1dd9c06b7d75890f192f9c772dc03bbd61b2ee29

### LINKED ISSUE #1463: [Collections\reverse] add support for PathLiteral values
[Collections\reverse] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Collections.nim#L1600

```text
                    push(newBlock(safeRepeat(x, y.i)))

    # TODO(Collections\reverse) add support for PathLiteral values
    #  labels: library, enhancement, easy
    builtin "reverse",
        alias       = unaliased,
        op          = opReverse,
```

590973f5546207d4556e70f6e0d64eb79485b091

### LINKED ISSUE #1464: [Collections\rotate] add support for PathLiteral values
[Collections\rotate] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Collections.nim#L1650

```text
                    push(newString(reversed(x.s)))

    # TODO(Collections\rotate) add support for PathLiteral values
    #  labels: library, enhancement, easy
    builtin "rotate",
        alias       = unaliased,
        op          = opNop,
```

a825bae1b98f4896b5becea4d06316dc86e8e9f1

### LINKED ISSUE #1465: [Collections\shuffle] add support for PathLiteral values
[Collections\shuffle] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Collections.nim#L1812

```text
                else: discard

    # TODO(Collections\shuffle) add support for PathLiteral values
    #  labels: library, enhancement, easy
    builtin "shuffle",
        alias       = unaliased,
        op          = opNop,
```

7b7ea1b3884e74b14415ca1cf94ec1045230ab72

### LINKED ISSUE #1466: [Collections\slice] add support for PathLiteral values
[Collections\slice] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Collections.nim#L1876

```text
                push(newInteger(0))

    # TODO(Collections\slice) add support for PathLiteral values
    #  labels: library, enhancement
    builtin "slice",
        alias       = unaliased,
        op          = opNop,
```

d9fafc1618eca20a0da209130f7770df8dcc72ae

### LINKED ISSUE #1467: [Collections\sort] add support for PathLiteral values
[Collections\sort] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Collections.nim#L1930

```text
    #  see: https://github.com/arturo-lang/arturo/pull/1045#issuecomment-1458960243
    #  labels: library, bug, critical

    # TODO(Collections\sort) add support for PathLiteral values
    #  labels: library, enhancement, easy
    builtin "sort",
        alias       = unaliased,
        op          = opNop,
```

0040b6d382a5b97851a41b78f4ce98182717d012

### LINKED ISSUE #1468: [Collections\split] add support for PathLiteral values
[Collections\split] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Collections.nim#L2122

```text
    #  Currently, simple split works fine - but using different attributes (at, every, by, etc) doesn't
    #  labels: library,bug

    # TODO(Collections\split) add support for PathLiteral values
    #  labels: library, enhancement
    builtin "split",
        alias       = unaliased,
        op          = opSplit,
```

b1ef90022d7bc558d549bbea0742a566dc805022

### LINKED ISSUE #1469: [Collections\squeeze] add support for PathLiteral values
[Collections\squeeze] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Collections.nim#L2279

```text
                else: push(x)

    # TODO(Collections\squeeze) add support for PathLiteral values
    #  labels: library, enhancement
    builtin "squeeze",
        alias       = unaliased,
        op          = opNop,
```

77328763502cd694f32a93c488b8f9ff2fd731f3

### LINKED ISSUE #1470: [Collections\take] add support for PathLiteral values
[Collections\take] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Collections.nim#L2343

```text
                    push(newBlock(ret))

    # TODO(Collections\take) add support for PathLiteral values
    #  labels: library, enhancement, easy
    builtin "take",
        alias       = unaliased,
        op          = opNop,
```

916c479f485382337d73e3e9aebb4fbcc25db72f

### LINKED ISSUE #1471: [Collections\unique] add support for PathLiteral values
[Collections\unique] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Collections.nim#L2469

```text
            push(newDictionary(occurences))

    # TODO(Collections\unique) add support for PathLiteral values
    #  labels: library, enhancement, easy
    builtin "unique",
        alias       = unaliased,
        op          = opNop,
ndex 34ec785e48..e2e9d716c4 100644
++ b/src/library/Colors.nim
```

5af85c20341f822fe595e30edd5946c5b8dc8220

### LINKED ISSUE #1480: [Crypto\crc] add support for PathLiteral values
[Crypto\crc] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Crypto.nim#L50

```text
    #----------------------------

    # TODO(Crypto\crc) add support for PathLiteral values
    #  labels: library, enhancement, easy
    builtin "crc",
        alias       = unaliased, 
        op          = opNop,
```

6247e5d39dc2b5067c77517026d4dd42549a79ad

### LINKED ISSUE #1481: [Crypto\decode] add support for PathLiteral values
[Crypto\decode] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Crypto.nim#L73

```text
                push(newString(x.s.crc32()))

    # TODO(Crypto\decode) add support for PathLiteral values
    #  labels: library, enhancement, easy
    builtin "decode",
        alias       = unaliased, 
        op          = opNop,
```

e9d6e8681c5dbf6e25d22336ac85d171af4f4db3

### LINKED ISSUE #1482: [Crypto\encode] add support for PathLiteral values
[Crypto\encode] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Crypto.nim#L112

```text
    #  Function doesn't really correspond to cryptography anymore. Or at least most of it. What should be done?
    #  labels: library, open discussion

    # TODO(Crypto\encode) add support for PathLiteral values
    #  labels: library, enhancement, easy
    builtin "encode",
        alias       = unaliased, 
        op          = opNop,
```

2e9f13744b9db363422dffccd853f08f3b54c86d

### LINKED ISSUE #1483: [Crypto\digest] add support for PathLiteral values
[Crypto\digest] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Crypto.nim#L189

```text
        #  would it be that useful to have md5/sha1 encoding capabilities through JavaScript?
        #  labels: library,enhancement,open discussion,web

        # TODO(Crypto\digest) add support for PathLiteral values
        #  labels: library, enhancement
        builtin "digest",
            alias       = unaliased, 
            op          = opNop,
ndex fb665495f8..aa92fef8d4 100644
++ b/src/library/Dates.nim
```

133459884c7fbbdf750f81c2d89743fcaadd3821

### LINKED ISSUE #1484: [Dates\after] add support for PathLiteral values
[Dates\after] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Dates.nim#L40

```text
    #----------------------------

    # TODO(Dates\after) add support for PathLiteral values
    #  labels: library, enhancement
    builtin "after",
        alias       = unaliased, 
        op          = opNop,
        rule        = PrefixPrecedence,
        description = "get date after given one using interval",
        args        = {
            "date"  : {Date, Literal}
        },
        attrs       = {
            "nanoseconds"   : ({Integer},"add given number of nanoseconds"),
```

04f3e7c3ad4de53cd6384303c915d4cef04d70a9

### LINKED ISSUE #1485: [Dates\before] add support for PathLiteral values
[Dates\before] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Dates.nim#L102

```text
                push(newDate(x.eobj + ti))

    # TODO(Dates\before) add support for PathLiteral values
    #  labels: library, enhancement
    builtin "before",
        alias       = unaliased, 
        op          = opNop,
ndex 06dbd22e9f..b58d57acae 100644
++ b/src/library/Paths.nim
```

e9234963bd1f45501bc1aab45f406b91b18f3980

### LINKED ISSUE #1486: [Paths\normalize] add support for PathLiteral values
[Paths\normalize] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Paths.nim#L231

```text
                push(newStringBlock(contents))
        
        # TODO(Paths\normalize) add support for PathLiteral values
        #  labels: library, enhancement, easy
        builtin "normalize",
            alias       = unaliased, 
            op          = opNop,
ndex 4e3cb00e1d..3618d2b57a 100644
++ b/src/library/Reflection.nim
```

a9338fa3fe694725f1332d74e4574d15545013dc

### LINKED ISSUE #1487: [Sets\difference] add support for PathLiteral values
[Sets\difference] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Sets.nim#L38

```text
    #----------------------------

    # TODO(Sets\difference) add support for PathLiteral values
    #  labels: library, enhancement
    builtin "difference",
        alias       = unaliased, 
        op          = opNop,
```

f5af58f2e3b07e8a594b7313e006c4bc35aa211c

### LINKED ISSUE #1488: [Sets\intersection] add support for PathLiteral values
[Sets\intersection] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Sets.nim#L79

```text
                    push(newBlock(toSeq(difference(toOrderedSet(x.a), toOrderedSet(y.a)))))

    # TODO(Sets\intersection) add support for PathLiteral values
    #  labels: library, enhancement
    builtin "intersection",
        alias       = VSymbol.intersection, 
        op          = opNop,
```

ded0e4c99cc3fa43012d598477eb3bc867a851c2

### LINKED ISSUE #1489: [Sets\powerset] add support for PathLiteral values
[Sets\powerset] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Sets.nim#L108

```text
                push(newBlock(toSeq(intersection(toOrderedSet(x.a), toOrderedSet(y.a)))))

    # TODO(Sets\powerset) add support for PathLiteral values
    #  labels: library, enhancement
    builtin "powerset",
        alias       = unaliased, 
        op          = opNop,
```

dbb4f423ebe8131b1612f76f857dfa80e480bfa8

### LINKED ISSUE #1490: [Sets\union] add support for PathLiteral values
[Sets\union] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Sets.nim#L131

```text
                push(newBlock(toSeq(powerset(toOrderedSet(x.a)).map((hs) => newBlock(toSeq(hs))))))

    # TODO(Sets\union) add support for PathLiteral values
    #  labels: library, enhancement
    builtin "union",
        alias       = VSymbol.union, 
        op          = opNop,
ndex 55e6e5fcc4..bafe07663c 100644
++ b/src/library/Strings.nim
```

0c53c287c69ba60e958942e99555adc103de56d2

### LINKED ISSUE #1491: [Strings\capitalize] add support for PathLiteral values
[Strings\capitalize] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Strings.nim#L118

```text
            push(newBlock(got))

    # TODO(Strings\capitalize) add support for PathLiteral values
    #  labels: library, enhancement, easy
    builtin "capitalize",
        alias       = unaliased, 
        op          = opNop,
```

411e3aa9a300677ad2ec1b85daee90ec7b77ecdc

### LINKED ISSUE #1492: [Strings\escape] add support for PathLiteral values
[Strings\escape] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Strings.nim#L146

```text
                    InPlaced.c = InPlaced.c.toUpper()

    # TODO(Strings\escape) add support for PathLiteral values
    #  labels: library, enhancement
    builtin "escape",
        alias       = unaliased, 
        op          = opNop,
```

dd4e3505d93b92cf645512403ced1c2759144cd2

### LINKED ISSUE #1493: [Strings\indent] add support for PathLiteral values
[Strings\indent] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Strings.nim#L208

```text
                    push(newString(strutils.escape(x.s)))

    # TODO(Strings\indent) add support for PathLiteral values
    #  labels: library, enhancement
    builtin "indent",
        alias       = unaliased, 
        op          = opNop,
```

b611faa4de398e42d9d8d3bfca4f4d791ae64ce3

### LINKED ISSUE #1494: [Strings\join] add support for PathLiteral values
[Strings\join] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Strings.nim#L274

```text
            push(newFloating(jaro(x.s,y.s)))    

    # TODO(Strings\join) add support for PathLiteral values
    #  labels: library, enhancement
    builtin "join",
        alias       = unaliased, 
        op          = opJoin,
```

04e7b0b9ec8cfde1c7fd2d79cc0d9101e85d7b0c

### LINKED ISSUE #1495: [Strings\outdent] add support for PathLiteral values
[Strings\outdent] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Strings.nim#L521

```text
                    push(newBlock(res))

    # TODO(Strings\outdent) add support for PathLiteral values
    #  labels: library, enhancement
    builtin "outdent",
        alias       = unaliased, 
        op          = opNop,
```

87f86a20e7bc4d2155a1410a431cc5f580788ed6

### LINKED ISSUE #1496: [Strings\pad] add support for PathLiteral values
[Strings\pad] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Strings.nim#L578

```text
                push(newString(unindent(x.s, count, padding))) 

    # TODO(Strings\pad) add support for PathLiteral values
    #  labels: library, enhancement, easy
    builtin "pad",
        alias       = unaliased, 
        op          = opNop,
```

d310a4a9494be2238daf6579cab4644013c06c45

### LINKED ISSUE #1497: [Strings\render] add support for PathLiteral values
[Strings\render] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Strings.nim#L632

```text
        #  the lack of proper RegEx libraries could be handled by using the newly-added JS helper functions
        #  labels: enhancement,library,web

        # TODO(Strings\render) add support for PathLiteral values
        #  labels: library, enhancement
        builtin "render",
            alias       = tilde, 
            op          = opNop,
            rule        = PrefixPrecedence,
            description = "render template with |string| interpolation",
            args        = {
                "template"  : {String,Literal}
            },
            attrs       = {
                "once"      : ({Logical},"don't render recursively"),
```

ca67b099734755da006d31e9cd48a3705becc83c

### LINKED ISSUE #1498: [Strings\replace] add support for PathLiteral values
[Strings\replace] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Strings.nim#L732

```text
    #  see: https://discord.com/channels/765519132186640445/829324913097048065/1078717850270842962
    #  labels: enhancement,library

    # TODO(Strings\replace) add support for PathLiteral values
    #  labels: library, enhancement, easy
    builtin "replace",
        alias       = unaliased, 
        op          = opReplace,
```

37a71698d8fa133970b4b3baa477d0b9e23a384b

### LINKED ISSUE #1499: [Strings\strip] add support for PathLiteral values
[Strings\strip] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Strings.nim#L790

```text
                            inc i

    # TODO(Strings\strip) add support for PathLiteral values
    #  labels: library, enhancement, easy
    builtin "strip",
        alias       = unaliased, 
        op          = opNop,
```

c6fc1981b949a873545bd26825c365a90c6cf7b4

### LINKED ISSUE #1500: [Strings\translate] add support for PathLiteral values
[Strings\translate] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Strings.nim#L829

```text
                InPlaced.s = strutils.strip(InPlaced.s, leading, trailing) 

    # TODO(Strings\translate) add support for PathLiteral values
    #  labels: library, enhancement, easy
    builtin "translate",
        alias       = unaliased, 
        op          = opNop,
```

64d9a3bf8c2e70f198ff44e708d9ac9256dff20b

### LINKED ISSUE #1501: [Strings\truncate] add support for PathLiteral values
[Strings\truncate] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Strings.nim#L860

```text
                InPlaced.s = InPlaced.s.multiReplace(replacements)

    # TODO(Strings\truncate) add support for PathLiteral values
    #  labels: library, enhancement, easy
    builtin "truncate",
        alias       = unaliased, 
        op          = opNop,
```

4a4161b6413aed08203f23478ac4d9693a3b005c

### LINKED ISSUE #1502: [Strings\wordwrap] add support for PathLiteral values
[Strings\wordwrap] add support for PathLiteral values

https://github.com/arturo-lang/arturo/blob/1c997951852f48f3bc64667e35f43532aaa768e0/src/library/Strings.nim#L937

```text
            elif xKind==Char: push(newChar(x.c.toUpper()))
            else: 
                ensureInPlaceAny()
                if InPlaced.kind==String:
                    InPlaced.s = InPlaced.s.toUpper()
                else:
                    InPlaced.c = InPlaced.c.toUpper()

    # TODO(Strings\wordwrap) add support for PathLiteral values
    #  labels: library, enhancement
    builtin "wordwrap",
        alias       = unaliased, 
        op          = opNop,
ndex 12242b9c7f..54dc786338 100644
++ b/src/library/Ui.nim
```

01c90d9fc822374f649e53ba7c450aa143c1994c

### PR DESCRIPTION
**Pull request by RickBarretto**
# Description

Basically, we have a looot of issues opened just to implement this.
So, let's go!

You can see all pending issues here: [Issues (:pathLiteral)][path-literal-issues]

- Fixes 
  - Fix #1502 
  - Fix #1501
  - Fix #1500 
  - Fix #1499 
  - Fix #1498 
  - Fix #1497 
  - Fix #1496 
  - Fix #1495
  - Fix #1494
  - Fix #1493
  - Fix #1492
  - Fix #1491
  - Fix #1490 
  - Fix #1489
  - Fix #1488 
  - Fix #1487
  - Fix #1486
  - Fix #1485 
  - Fix #1484
  - Fix #1483 
  - Fix #1482 
  - Fix #1481
  - Fix #1480
  - Fix #1471 
  - Fix #1470
  - Fix #1469
  - Fix #1468 
  - Fix #1467 
  - Fix #1466 
  - Fix #1465 
  - Fix #1464 
  - Fix #1463
  - Fix #1462 
  - Fix #1461 
  - Fix #1460
  - Fix #1459
  - Fix #1458 
  - Fix #1457 
  - Fix #1456 
  - Fix #1455 
  - Fix #1454
  - Fix #1453 
  - Fix #1452 
  - Fix #1451 
  - Fix #1450

## Type of change

- [x] Unit tests (added or updated unit-tests)
- [x] Enhancement (implementation update, or general performance enhancements)

---

> [!NOTE]
> Tests added are property-based, and they don't checks if the result is correct,
> this just check if the result is the same of `:literal`

[path-literal-issues]: https://github.com/arturo-lang/arturo/issues?q=is%3Aissue+is%3Aopen+label%3A%3ApathLiteral

### CODE REVIEW

**Comment by drkameleon** [comment]
Awesome! 🚀 

P.S. I've spent 2 hours already trying to properly implement this - super nice-looking admittedly `[!NOTE]` (and related) magic for pkgr.art! haha

**Comment by RickBarretto** [comment]
Completed for the Strings' Lib!

**Comment by RickBarretto** [comment]
Completed for the Sets' Lib!

**Comment by celtic-coder** [comment]
> Awesome! 🚀
> 
> P.S. I've spent 2 hours already trying to properly implement this - super nice-looking admittedly - `[!NOTE]` (and related) magic for pkgr.art! haha

Good work! 👍

**Comment by RickBarretto** [comment]
Completed for the Paths' Lib!

**Comment by RickBarretto** [comment]
Completed for the Dates' Lib!

**Comment by RickBarretto** [comment]
Completed for the Crypto' Lib!

**Comment by RickBarretto** [comment]
> [!WARNING]
> - [6f08ef5](https://github.com/arturo-lang/arturo/pull/1563/commits/6f08ef5bd5efe5a584054b9122b08526af8e5edf) does not fix #1479, but #1471, 
> - and [34268e7](https://github.com/arturo-lang/arturo/pull/1563/commits/34268e74ef8ff7ad9683b90e1b20ba82866ba0f8) does not fix #1478, but #1470.

**Comment by RickBarretto** [comment]
Finished! 🙂

**Review by drkameleon — APPROVED** [review]
What an extreme job!!! 😲 🚀 

I wouldn't imagine all that being done in one go, but... wow!!

Needless to say, the addition of unit-tests as well is extremely important too. For consistency, and to make sure that we are not adding bugs instead of features.

What can I say... Pure awesomeness! 😄

**Comment by drkameleon** [comment]
And of course...

Ready to merge! 🚀

**Pull request merged**
