### PR TITLE
Sanitize Logical values

### PR DESCRIPTION
**Pull request by drkameleon**
# Description

Right now, especially after #800, the `VLogical` value type seems a bit obsolete.

The two have to be unified as smoothly as possible - ~~potentially without the need of a distinct type whatsoever~~.

## Type of change

- [x] Code cleanup

### CODE REVIEW

**Comment by drkameleon** [comment]
Looking good and rather tidy. Will have another look by tomorrow morning and - if everything keeps looking good, this will be merged.

@beef331 If you have any suggestion, or think I'm doing something terribly... off, feel free to let me know! 😉

**Comment by beef331** [comment]
Other than pretending Nim is C with `(ValueFlags) myVal)` instead of `ValueFlags(myVal)` or `ValueFlags myVal` looks good to me.

**Comment by drkameleon** [comment]
> Other than pretending Nim is C

I plead totally guilty! haha

Thanks for the feedback! 😄

**Comment by drkameleon** [comment]
Ready to merge! 🚀

**Pull request merged**
