### PR TITLE
Add WindowsMsys2 artifacts for releases

### PR DESCRIPTION
**Pull request by RickBarretto**
# Description

This pull request complements [Add Msys2 auto-install support #1](https://github.com/arturo-lang/arturo-lang.io/pull/1) PR on [arturo-lang/arturo-lang.io](https://github.com/arturo-lang/arturo-lang.io).

Fixes [Add Msys2 auto-install support #1](https://github.com/RickBarretto/arturo/issues/1#issue-1382319355), (issue that I added on my fork)

## Type of change

- [x] Add WindowsMsys2 artifacts to be uploaded on releases. This releases are packages into `.tar.gz`, because Msys doesn't support unpack `zip` files by default.
  - This releases are the same of Windows, but with a different package file extension.
  - Benefits: auto-install for Windows using Msys2

Ps.: I think it needs a review.

### CODE REVIEW

**Comment by drkameleon** [comment]
@RickBarretto Awesome job!

Would you mind adding the exact same changes to the normal CI build to (with the artifacts and everything I mean).

Since it's running for every PR, it will be the easiest way for both of us to verify whether it's working or not. 😉

**Comment by RickBarretto** [comment]
Yes, I can. The builds and tests are the same for Windows.
For Msys2, just the packaging will be different.

So I must to add: `Create Msys2 artifact (version)` and `Upload Msys2 Artifacts`

**Comment by RickBarretto** [comment]
> Since it's running for every PR, it will be the easiest way for both of us to verify whether it's working or not. 😉

If do you want, I can do it too. But, it's the same configuration of Windows.
The only difference between both is the packaging, where `.tar.gz` will be generated instead `.zip`.

I'll create a commit adding `msys.yml`

**Comment by RickBarretto** [comment]
> Since it's running for every PR, it will be the easiest way for both of us to verify whether it's working or not. 😉

I read the [windows.yml](https://github.com/arturo-lang/arturo/blob/master/.github/workflows/windows.yml), and it'll work for Msys without any changes. (Really)

As I said, Msys and Windows must to be the same package. But, we need a `.tar.gz` for Msys, so the only difference is on releases.
A default Windows' user''ll have WinRar in PC, it can unpack both zip and tar.gz, but it must to be made manually. As I did my first time. I opened the explorer, unpacked and moved to ~/.arturo/bin. Msys unpacking a tar.gz would do it automatically, because it's using POSIX environment, that have the tar application.

Note, I said WinRar can unpack both. But, I don't want to change Windows CI directly, to avoid making a mess.
If when unpack `WindowsMsys2` and `Windows` are the same, it's working.

If it's working in Windows CI, it's is working in Msys CI. Really. If I would do a `msys.yml` it would be the same file, just a copy past without changes.

**Comment by drkameleon** [comment]
Awesome, I get it!

So, there is basically no need for this.

Congrats on the great job & thanks for the thorough explanation.

I'm going through it one more time and merge it. 🚀

**Comment by drkameleon** [comment]
Looks fine! 😄 

You're about to become on of the very few members of the... select group of Arturo contributors. lol

Thanks again! Keep it going!!

**Comment by RickBarretto** [comment]
I'll learn more about Nim (it was already on my plans). So, in future, if you want I can collaborate. 😄

**Comment by RickBarretto** [comment]
@drkameleon, I'm seeing now.
I must to update [Nightlytoo](https://github.com/arturo-lang/nightly/blob/master/.github/workflows/build.yml).
Here I must to do a copy past of windows' section, and change the packer from 7z to tar. 😉

**Comment by drkameleon** [comment]
> I'll learn more about Nim (it was already on my plans). So, in future, if you want I can collaborate. 😄

Absolutely!

If you are familiar with Python (which - as far as I can see - you are; I'm not at all lol), Nim should come quite naturally to you. It shares many, many characteristics - only in a compiled-language environment, and with C behind. But definitely, it shouldn't take you long before you are quite familiar with it.

Also, I've tried to organize Arturo's codebase in such a way that's clean enough (including for me), so that should help too.

Regarding what you could work on, I'd suggest having a look into the list of open issues (there are lots: some quite complex, some easier, especially the ones that are documentation-related). For me, perhaps the easiest idea to work on would be to add some library function you think is missing: tell me about it to see whether we are on the same page, and you could start working on something, on your own, by kindof-imitating what's being done in different library functions. (they can definitely serve as some sort of inspiration! :wink)

**Re: nightlies**

I missed that too... I pretty much forget they exist lol. But they do. :)

**Comment by celtic-coder** [comment]
Good work, @RickBarretto! This is very useful for Windows users. Thanks for your efforts. Well done! 😄

**Comment by RickBarretto** [comment]
@drkameleon 
Yes! I have experience with Python and some with C. I'm current learning C from "Beej Guide to C" and "Modern C" books.
I heard about Nim, about of 2 months ago and I loved the idea.
Unfortunately I couldn't pay that much attention to this awesome language, due to other personal studies. 

Nim is easy to learn, I think. My problem would only be in better managing my time. 
But, yeah, I'll try add some features. I'm missing RSA and AES crypto algorithms in Arturo Library, for example. 😎 

---
And
> Good work, @RickBarretto! This is very useful for Windows users. Thanks for your efforts. Well done! 😄

Thank you, @celtic-coder! 🚀

**Pull request merged**
