### PR TITLE
Debug Package Manager on Windows

### PR DESCRIPTION
**Pull request by drkameleon**
# Description

This is an attempt to discover (and fix) what it is exactly that makes our Package Manager not work on Windows.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by drkameleon** [comment]
@RickBarretto I've made some changes with the paths (which I think may be one of the culprits).

Could you please try the binary from here and let me know if this is now working?

Preferrably, I'd try it like this (to see what breaks - if it does - and what doesn't):

- `arturo -p list`
- `arturo -p remote`
- `arturo -p install dummy`
- `arturo -p list` (all of the commands from here, only if the installation succeeded 😉 )
- `arturo -p install dummy 0.0.3` (if installation succeeded)
- `arturo -p list`
- `arturo -p uninstall dummy` (if installation succeeded)

Let's see what we've managed to do here! 🚀

**Comment by RickBarretto** [comment]
It still broken on Windows...

```
PS C:\msys64\home\dev\arturo> ./bin/arturo -p list

! No local packages found

  You may find the complete list at https://pkgr.art
  or use: arturo --package remote

PS C:\msys64\home\dev\arturo> ./bin/arturo -p remote

  Remote packages

--------------------------------------------------------------------------------
  Package                       Description
--------------------------------------------------------------------------------
- dummy                         This package will serve merely as
                                test for Arturo's package manager

  1 packages found.

PS C:\msys64\home\dev\arturo> ./bin/arturo -p install dummy

  Install package

- Querying registry...
- Downloading spec: dummy.pkgr.art ✔
- Downloading sources
! Something went wrong

  Unable to open file

PS C:\msys64\home\dev\arturo> ./bin/arturo -p list         

! No local packages found

  You may find the complete list at https://pkgr.art
  or use: arturo --package remote

PS C:\msys64\home\dev\arturo> ./bin/arturo -p install dummy 0.0.3

  Install package

- Querying registry...
- Downloading spec: dummy.pkgr.art ✔
- Downloading sources
! Something went wrong

  Unable to open file

PS C:\msys64\home\dev\arturo> ./bin/arturo -p list

! No local packages found

  You may find the complete list at https://pkgr.art
  or use: arturo --package remote

PS C:\msys64\home\dev\arturo> ./bin/arturo -p uninstall dummy

  Uninstall package


! The package was not found

  You may see the list of available packages
  by using: arturo --package list

PS C:\msys64\home\dev\arturo>
```

**Comment by RickBarretto** [comment]
I'll try it again. I think some things wasn't updated when I changed to this branch.

**Comment by drkameleon** [comment]
So... in the end, what is the conclusion? Is it stuck at the installation stage? 🤔

**Comment by drkameleon** [comment]
Totally newbie (<- disclaimer lol) try on a vanilla, nothing-installed-whatsoever, Windows 2022 server cloud VM.

Screenshot 2023-12-11 at 14 38 03

Screenshot 2023-12-11 at 14 38 29

**Comment by drkameleon** [comment]
And, after copy-pasting the certificate (inside the binary's folder) from here: https://curl.se/ca/cacert.pem (as per: https://github.com/nim-lang/Nim/issues/782#issuecomment-785531690).

Screenshot 2023-12-11 at 14 44 20

In that case, there seem to be no SSL-related errors, although there's still sth wrong... Hmm... 🤔

**Comment by drkameleon** [comment]
After manually creating (`mkdir`) an `tmp` directory inside my supposed HOME directory (`\Users\administrator\Desktop\.arturo`):

Screenshot 2023-12-11 at 14 48 10

**Comment by drkameleon** [comment]
And working normally - apparently: 🚀 

Screenshot 2023-12-11 at 14 50 40

**Comment by drkameleon** [comment]
And apparently, it's finally working!! 🚀 

-----

**Viewing local/remote packages & Installing a package from scratch:**

Screenshot 2023-12-11 at 16 41 10

**Installing a specific package version:**

Screenshot 2023-12-11 at 16 41 35

**Uninstalling a specific package version:**

Screenshot 2023-12-11 at 16 41 58

**Complete uninstalling a package:**

Screenshot 2023-12-11 at 16 42 13

**Updating packages:**

Screenshot 2023-12-11 at 16 42 36

**Comment by drkameleon** [comment]
@RickBarretto I think I've finally made it - with your help & input ofc! 🚀 🚀 

If you have time and check it, once you give me the green light 🟢, I'm merging it! 😉  (you may actually do it as a proper "PR Review", so that you see what this is about - no big deal really, but still...)

**Comment by RickBarretto** [comment]
For some reason, this broke again... Curious, I'm trying to figure out why.

**Comment by RickBarretto** [comment]
Tested, the reason of the error is: if there is a `pkg.zip` folder, it'll break and will be unable to open the file.

**Comment by drkameleon** [comment]
> Tested, the reason of the error is: if already there is a `pkg.zip` folder before downloading the package, it'll break and will be unable to open the file.

Hmm... Good catch. I'll have a look...

And, of course: Thanks a lot! 😉 🚀

**Comment by RickBarretto** [comment]
> Hmm... Good catch. I'll have a look...
> And, of course: Thanks a lot! 😉 🚀

You're welcome! 🙂

**Review by RickBarretto — CHANGES_REQUESTED** [review]
`@mini` builds' REPL are broken.

image

**Comment by drkameleon** [comment]
> `@mini` build's REPL is broken.
> 
> image

And... Everything *should* be fixed (I just test the mini + full builds): the one has no packages/`import` (and hopefully no errors) and the other is all-inclusive. 😉

**Review by RickBarretto — APPROVED** [review]
I just finished to test it for `@mini` and `@full` builds! Well done work! 🚀 

Ready to merge, so?

**Comment by drkameleon** [comment]
> I just finished to test it for `@mini` and `@full` builds! Well done work! 🚀
> 
> Ready to merge, so?

Perfect!! Thanks! Let's go! 🚀

**Pull request merged**
