### PR TITLE
[Helpers\helper] Refactor helper.nim

### PR DESCRIPTION
**Pull request by RickBarretto**
# Description

This PR cleans `helper.nim` up and refactor some functions, making them more readable and maintainable.

- Related to #596

## Type of change

- [x] Code cleanup
- [ ] Unit tests (added or updated unit-tests)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (implementation update, or general performance enhancements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation (documentation-related additions)

### CODE REVIEW

**Comment by RickBarretto** [comment]
@drkameleon I have two questions to do.
1) What do you think about this?
2) Examples are strictly necessary to be generated when it's a function? Or our docgen will just ignore it? I'm afraid of it break the documentation generation, but I can decouple it again if you tell me...

**Comment by RickBarretto** [comment]
@drkameleon, the error it's emitting is this:

image

IDK if this is related to any modification on `helper.nim`.

**Comment by drkameleon** [comment]
> @drkameleon I have two questions to do.
> 
> 1. What do you think about this?
> 2. Are "examples" strictly necessary to be generated when it's a function? ([group DOCGEN's available attributes](https://github.com/arturo-lang/arturo/pull/1273/commits/21a992d808d22cc7592c5d38e95c9b2aec279398)) Or will our docgen just ignore it? I'm afraid about break the documentation generation, but I can decouple it again if you tell me...

1. Great idea to be honest (I'll have to look at the final rewrite, but I I like your idea!)
2. Examples are generated only for docgen (basically, when I want to generate the documentation, I first build Arturo accordingly - with `./build.nims docs` - and then use *that* binary for the doc generation). At some point, the examples formed part of all normal binaries too; but honestly having all this text data just packed into every binary, in case sb needs it... I don't know. Regarding "breaking" it... well, go ahead, and we'll see later! haha 😉

**Comment by drkameleon** [comment]
> @drkameleon, the error it's emitting is this:
> 
> image
> 
> IDK if this is related to any modification on `helper.nim`.

Hmm... it doesn't seem like it's related at all - to me, it looks like one of the various leftover bugs with the Quantity implementation (unfortunately). I'll have to go through them one by one, I guess it could be my very next PR ;)

**Comment by RickBarretto** [comment]
@drkameleon finished!

If you think I should do more things here, you can tell me!

**Comment by drkameleon** [comment]
P.S. I haven't forgotten about this. I just want to take my time and look into properly before merging (and given the amount of work that I've had lately, well... I guess I decided to wait a tiny bit so that I don't do it in a hurry). But I *will* ;)

**Review by drkameleon — APPROVED** [review]
After... almost 2 months, I finally got around to have a look into it lol.

Well, the truth is it's totally looking good (if I spot anything I don't particularly like, I'll look into it at a different moment too, but I really doubt it).

Very organized and clean! 😉

**Comment by drkameleon** [comment]
Ready to merge! 🚀

**Pull request merged**
