### PR TITLE
[Files/read] add support for different delimiters when in `.csv` mode

### LINKED ISSUE #1016: [Files/read] add support for different delimiters when in `.csv` mode
[Files/read] add support for different delimiters when in `.csv` mode

this could be something as simple as `.with:` or `.delimiter:`, or `.delimited:`

also see: https://github.com/arturo-lang/arturo/pull/1008#issuecomment-1450571702

https://github.com/arturo-lang/arturo/blob/03cc988ad88d59c759e3d5194bb7c456dd9cc57c/src/library/Files.nim#L277

```text
                    push(VNULL)

        # TODO(Files/read) add support for different delimiters when in `.csv` mode
        #  this could be something as simple as `.with:` or `.delimiter:`, or `.delimited:`
        #  also see: https://github.com/arturo-lang/arturo/pull/1008#issuecomment-1450571702
        #  labels:library,enhancement
        builtin "read",
            alias       = doublearrowleft, 
            op          = opNop,
```

fe984a066b0d702fe745497d1d171a68dbcebc1c

### PR DESCRIPTION
**Pull request by RickBarretto**
Fixes #1016

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Update/Add unit-tests
- [x] This change requires a documentation update

### CODE REVIEW

**Comment by RickBarretto** [comment]
Finished!

**Comment by drkameleon** [comment]
@RickBarretto Awesome! 😉 

I'll have a look into all your work by tomorrow and merge accordingly! Keep going!! 🚀

**Review by drkameleon — APPROVED** [review]
OK. Great job! 👍 

Cleanly done, all very organized and obvious, attributes in place. You even added the relevant unit-tests!

What can I say... awesome! 😉

**Comment by drkameleon** [comment]
Ready to merge! 🚀

**Pull request merged**
