### PR TITLE
Solve LLP64-related GMP issues on Windows

### PR DESCRIPTION
**Pull request by drkameleon**
# Description

- **Useful read:** https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models
- **See:** https://github.com/arturo-lang/arturo/issues/979#issuecomment-1441618978

Fixes: #979 
Fixes: #978 
Fixes: #977 
Fixes: #976 
Fixes: #975 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by drkameleon** [comment]
**Modified RC code:**

```red
getIntegerType: function [int][
    (integer?.big int)? -> "big" -> "normal"
]

customProduct: function [idx, lst][
    result: 1
    loop lst 'item [
        print ["Term No" idx "-> multiplying:" result "(" getIntegerType result ")" "with:" item "(" getIntegerType item ")"]
        result: result * item
        print ["result:" result]
    ]
    print "------"
    return result
]

sylvester: function [lim][
    result: [2]
    loop 2..lim 'x [
        'result ++ customProduct x-1 result
    ]
    return result
]
lst: sylvester 10

print "First 10 terms of the Sylvester sequence:"
print lst
print ""

sumRep: round sum map lst => [1 // &]

print "Sum of the reciprocals of the first 10 items:"
print sumRep
```

**Output @ macOS:**

```
Term No 1 -> multiplying: 1 ( normal ) with: 2 ( normal ) 
result: 2 
------
Term No 2 -> multiplying: 1 ( normal ) with: 2 ( normal ) 
result: 2 
Term No 2 -> multiplying: 2 ( normal ) with: 2 ( normal ) 
result: 4 
------
Term No 3 -> multiplying: 1 ( normal ) with: 2 ( normal ) 
result: 2 
Term No 3 -> multiplying: 2 ( normal ) with: 2 ( normal ) 
result: 4 
Term No 3 -> multiplying: 4 ( normal ) with: 4 ( normal ) 
result: 16 
------
Term No 4 -> multiplying: 1 ( normal ) with: 2 ( normal ) 
result: 2 
Term No 4 -> multiplying: 2 ( normal ) with: 2 ( normal ) 
result: 4 
Term No 4 -> multiplying: 4 ( normal ) with: 4 ( normal ) 
result: 16 
Term No 4 -> multiplying: 16 ( normal ) with: 16 ( normal ) 
result: 256 
------
Term No 5 -> multiplying: 1 ( normal ) with: 2 ( normal ) 
result: 2 
Term No 5 -> multiplying: 2 ( normal ) with: 2 ( normal ) 
result: 4 
Term No 5 -> multiplying: 4 ( normal ) with: 4 ( normal ) 
result: 16 
Term No 5 -> multiplying: 16 ( normal ) with: 16 ( normal ) 
result: 256 
Term No 5 -> multiplying: 256 ( normal ) with: 256 ( normal ) 
result: 65536 
------
Term No 6 -> multiplying: 1 ( normal ) with: 2 ( normal ) 
result: 2 
Term No 6 -> multiplying: 2 ( normal ) with: 2 ( normal ) 
result: 4 
Term No 6 -> multiplying: 4 ( normal ) with: 4 ( normal ) 
result: 16 
Term No 6 -> multiplying: 16 ( normal ) with: 16 ( normal ) 
result: 256 
Term No 6 -> multiplying: 256 ( normal ) with: 256 ( normal ) 
result: 65536 
Term No 6 -> multiplying: 65536 ( normal ) with: 65536 ( normal ) 
result: 4294967296 
------
Term No 7 -> multiplying: 1 ( normal ) with: 2 ( normal ) 
result: 2 
Term No 7 -> multiplying: 2 ( normal ) with: 2 ( normal ) 
result: 4 
Term No 7 -> multiplying: 4 ( normal ) with: 4 ( normal ) 
result: 16 
Term No 7 -> multiplying: 16 ( normal ) with: 16 ( normal ) 
result: 256 
Term No 7 -> multiplying: 256 ( normal ) with: 256 ( normal ) 
result: 65536 
Term No 7 -> multiplying: 65536 ( normal ) with: 65536 ( normal ) 
result: 4294967296 
Term No 7 -> multiplying: 4294967296 ( normal ) with: 4294967296 ( normal ) 
result: 18446744073709551616 
------
Term No 8 -> multiplying: 1 ( normal ) with: 2 ( normal ) 
result: 2 
Term No 8 -> multiplying: 2 ( normal ) with: 2 ( normal ) 
result: 4 
Term No 8 -> multiplying: 4 ( normal ) with: 4 ( normal ) 
result: 16 
Term No 8 -> multiplying: 16 ( normal ) with: 16 ( normal ) 
result: 256 
Term No 8 -> multiplying: 256 ( normal ) with: 256 ( normal ) 
result: 65536 
Term No 8 -> multiplying: 65536 ( normal ) with: 65536 ( normal ) 
result: 4294967296 
Term No 8 -> multiplying: 4294967296 ( normal ) with: 4294967296 ( normal ) 
result: 18446744073709551616 
Term No 8 -> multiplying: 18446744073709551616 ( big ) with: 18446744073709551616 ( big ) 
result: 340282366920938463463374607431768211456 
------
Term No 9 -> multiplying: 1 ( normal ) with: 2 ( normal ) 
result: 2 
Term No 9 -> multiplying: 2 ( normal ) with: 2 ( normal ) 
result: 4 
Term No 9 -> multiplying: 4 ( normal ) with: 4 ( normal ) 
result: 16 
Term No 9 -> multiplying: 16 ( normal ) with: 16 ( normal ) 
result: 256 
Term No 9 -> multiplying: 256 ( normal ) with: 256 ( normal ) 
result: 65536 
Term No 9 -> multiplying: 65536 ( normal ) with: 65536 ( normal ) 
result: 4294967296 
Term No 9 -> multiplying: 4294967296 ( normal ) with: 4294967296 ( normal ) 
result: 18446744073709551616 
Term No 9 -> multiplying: 18446744073709551616 ( big ) with: 18446744073709551616 ( big ) 
result: 340282366920938463463374607431768211456 
Term No 9 -> multiplying: 340282366920938463463374607431768211456 ( big ) with: 340282366920938463463374607431768211456 ( big ) 
result: 115792089237316195423570985008687907853269984665640564039457584007913129639936 
------
First 10 terms of the Sylvester sequence:
2 2 4 16 256 65536 4294967296 18446744073709551616 340282366920938463463374607431768211456 115792089237316195423570985008687907853269984665640564039457584007913129639936 

Sum of the reciprocals of the first 10 items:
1.0
```

**Output @ Windows:**

```
Term No 1 -> multiplying: 1 ( normal ) with: 2 ( normal )
result: 2
------
Term No 2 -> multiplying: 1 ( normal ) with: 2 ( normal )
result: 2
Term No 2 -> multiplying: 2 ( normal ) with: 2 ( normal )
result: 4
------
Term No 3 -> multiplying: 1 ( normal ) with: 2 ( normal )
result: 2
Term No 3 -> multiplying: 2 ( normal ) with: 2 ( normal )
result: 4
Term No 3 -> multiplying: 4 ( normal ) with: 4 ( normal )
result: 16
------
Term No 4 -> multiplying: 1 ( normal ) with: 2 ( normal )
result: 2
Term No 4 -> multiplying: 2 ( normal ) with: 2 ( normal )
result: 4
Term No 4 -> multiplying: 4 ( normal ) with: 4 ( normal )
result: 16
Term No 4 -> multiplying: 16 ( normal ) with: 16 ( normal )
result: 256
------
Term No 5 -> multiplying: 1 ( normal ) with: 2 ( normal )
result: 2
Term No 5 -> multiplying: 2 ( normal ) with: 2 ( normal )
result: 4
Term No 5 -> multiplying: 4 ( normal ) with: 4 ( normal )
result: 16
Term No 5 -> multiplying: 16 ( normal ) with: 16 ( normal )
result: 256
Term No 5 -> multiplying: 256 ( normal ) with: 256 ( normal )
result: 65536
------
Term No 6 -> multiplying: 1 ( normal ) with: 2 ( normal )
result: 2
Term No 6 -> multiplying: 2 ( normal ) with: 2 ( normal )
result: 4
Term No 6 -> multiplying: 4 ( normal ) with: 4 ( normal )
result: 16
Term No 6 -> multiplying: 16 ( normal ) with: 16 ( normal )
result: 256
Term No 6 -> multiplying: 256 ( normal ) with: 256 ( normal )
result: 65536
Term No 6 -> multiplying: 65536 ( normal ) with: 65536 ( normal )
result: 4294967296
------
Term No 7 -> multiplying: 1 ( normal ) with: 2 ( normal )
result: 2
Term No 7 -> multiplying: 2 ( normal ) with: 2 ( normal )
result: 4
Term No 7 -> multiplying: 4 ( normal ) with: 4 ( normal )
result: 16
Term No 7 -> multiplying: 16 ( normal ) with: 16 ( normal )
result: 256
Term No 7 -> multiplying: 256 ( normal ) with: 256 ( normal )
result: 65536
Term No 7 -> multiplying: 65536 ( normal ) with: 65536 ( normal )
result: 4294967296
Term No 7 -> multiplying: 4294967296 ( normal ) with: 4294967296 ( normal )
result: 0
------
Term No 8 -> multiplying: 1 ( normal ) with: 2 ( normal )
result: 2
Term No 8 -> multiplying: 2 ( normal ) with: 2 ( normal )
result: 4
Term No 8 -> multiplying: 4 ( normal ) with: 4 ( normal )
result: 16
Term No 8 -> multiplying: 16 ( normal ) with: 16 ( normal )
result: 256
Term No 8 -> multiplying: 256 ( normal ) with: 256 ( normal )
result: 65536
Term No 8 -> multiplying: 65536 ( normal ) with: 65536 ( normal )
result: 4294967296
Term No 8 -> multiplying: 4294967296 ( normal ) with: 4294967296 ( normal )
result: 0
Term No 8 -> multiplying: 0 ( big ) with: 0 ( big )
result: 0
------
Term No 9 -> multiplying: 1 ( normal ) with: 2 ( normal )
result: 2
Term No 9 -> multiplying: 2 ( normal ) with: 2 ( normal )
result: 4
Term No 9 -> multiplying: 4 ( normal ) with: 4 ( normal )
result: 16
Term No 9 -> multiplying: 16 ( normal ) with: 16 ( normal )
result: 256
Term No 9 -> multiplying: 256 ( normal ) with: 256 ( normal )
result: 65536
Term No 9 -> multiplying: 65536 ( normal ) with: 65536 ( normal )
result: 4294967296
Term No 9 -> multiplying: 4294967296 ( normal ) with: 4294967296 ( normal )
result: 0
Term No 9 -> multiplying: 0 ( big ) with: 0 ( big )
result: 0
Term No 9 -> multiplying: 0 ( big ) with: 0 ( big )
result: 0
------
First 10 terms of the Sylvester sequence:
2 2 4 16 256 65536 4294967296 0 0 0

Sum of the reciprocals of the first 10 items:
1.0
```

-----

The key here is: `multiplying: 4294967296 ( normal ) with: 4294967296 ( normal )`, we are multiplying to normal-type Integers but the result will obviously *not* fit into a normal-type Integer, so it has to be upgraded to a GMP BigNum.

For some reason, [this OverflowDefect](https://github.com/arturo-lang/arturo/blob/master/src/vm/values/value.nim#L1158) is *never* triggered on Windows, no matter what.

Is this a Nim bug? 🤔

**Comment by drkameleon** [comment]
Further reduction of the issue
======

**@ macOS**

```
$> 4294967296 * 4294967296
OVERFLOW!!!
=> 18446744073709551616
```

@ Windows

```
$> 4294967296 * 4294967296
OVERFLOW!!!
=> 0
```

So, the OverflowDefect *is* triggered in the end. The result is messed up. But it should be rather straightforward: https://github.com/arturo-lang/arturo/blob/master/src/vm/values/value.nim#L921 🤔

**Comment by drkameleon** [comment]
**Last bet:**

The issue has to do with our GMP wrapper itself 😢 : https://github.com/arturo-lang/arturo/blob/master/src/helpers/bignums.nim#L83-L98

Or... better put: with Windows having a different size for `clong`s and `int`s. Hence, the whole LLP64-related commented out code (which, obviously, shouldn't have been completely omitted...)

In a few words: [Welcome to the Jungle](https://www.youtube.com/watch?v=o1tj2zJ2Wvg)! lol

**Comment by drkameleon** [comment]
Culprit spotted: https://github.com/arturo-lang/arturo/blob/debug-overflowing-multiplications/src/helpers/bignums.nim#L97-L98

Now, let's see how we can go about fixing this... 🤔

**Comment by drkameleon** [comment]
✅  Sylvester's sequence for Windows solved! 🎉 

And... coincidentally, thanks to @RickBarretto's persistence over a seemingly insignificant issue that I had totally forgotten about (lol), we spotted a *very* important bug with GMP + Windows (that is: the full x86_64 build)

There are similar tweaks to be done in that exact direction, but in the meantime... let's see whether this fix can possibly make other failing RC tests work too! 🚀

**Comment by drkameleon** [comment]
Phewww... That was a challenging one!

So, so, so... I *think* most (if not all) GMP/LLP64-related on Windows should be solved by now. 

In case anything related pops up again, at least we'll have this PR and the whole discussion around for reference. And, of course, any closed issue can be re-opened if needed.

That being said... 🥁

-----

Ready to merge! 🚀

**Comment by RickBarretto** [comment]
Wow, really! Awesome work here! I have no words to express myself...
Really, awesome!! :rocket:

---

> In case anything related pops up again, at least we'll have this PR and the whole discussion around for reference. And, of course, any closed issue can be re-opened if needed.

I see it as a good idea.

**Pull request merged**
