### PR TITLE
[scripts\update.art] - rewrite

### LINKED ISSUE #1181: [CLI] - Update does not work
**Description**
Update arturo via cli breaks.

**To Reproduce**

```
$ arturo -u
>> Runtime | cannot perform download -> :block
     error | incorrect argument type for first parameter
           | accepts  \:string
```

**Expected behavior**
Arturo updated to the lastest version and no runtime error.

**Desktop**
 - OS: `Manjaro - linux`
 - Version `0.9.83`

**Additional context**
[This message from Discord][discord]

[discord]: https://discord.com/channels/765519132186640445/765519132186640448/1104010970633863198

### PR DESCRIPTION
**Pull request by RickBarretto**
# Description

Rewrites updater that is broken as said in #1181.
- [x] Rewrite into smaller functions
- [x] Ensure that it's working 
- [x] Add functions' documentation
- [ ] ~Add mini-builds' support~ (It doesn't have SSL)
- [ ] ~Add Windows' support~ (Nightly builds doesn't have Windows' binaries)

## Related
- Fixes #1181

## Type of change

- [x] Code cleanup
- [x] Bug fix ([Breaking changes][breaking-changes-comment])
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Add/Update unit-tests (How can I properly test it?)

[breaking-changes-comment]: https://github.com/arturo-lang/arturo/pull/1182#issuecomment-1538706614

### CODE REVIEW

**Comment by RickBarretto** [comment]
@drkameleon, before I proceed, I have got two issues.
1. As nightly build doesn't support Windows, I'll disable this for while
2. Does mini-builds support this feature? Or just full?
    - As it's now it's updating just full-builds.

**Comment by RickBarretto** [comment]
It has a little breaking change. It replaces the binary that is running at the moment, instead of the global...
I think that it's the right behavior in this situation.

**Comment by RickBarretto** [comment]
BTW, I tried to add support for mini-builds, I noticed it doesn't have SSL, so it can't do this kind of task...

**Comment by RickBarretto** [comment]
You can consider this as done, but if you think it's missing something, feel free to say.
Also, other idea would be add `stable` updates too...

**Comment by RickBarretto** [comment]
I'm marking this as done to not diverge so much from main branch.
So, I'll implement missing features soon in other PR. :wink:

**Comment by drkameleon** [comment]
Merging this as complete (and in case we want to add/fix anything, I guess we can doing via a different PR; the feature wasn't working at all any way... so... 😉 )

Thanks!

**Review by drkameleon — APPROVED** [review]

**Comment by drkameleon** [comment]
And... ready to merge! 🚀

**Pull request merged**
