### PR TITLE
[Core\pop] rename `pop` to `unstack` and fix `SIGSEGV` error

### LINKED ISSUE #1027: [Core/pop] should be probably renamed
[Core/pop] should be probably renamed

`pop` could easily do what a `pop` normally does, and that would mean

a built-in method in the Collections module that pops/deletes an element from

a given block/collection and returns it

This one refers to the stack and it could be quite confusing.

So, preferrably, IMHO, this should be renamed to something like: `unstack`, `destack`, etc

label: library, enhancement, open discussion

https://github.com/arturo-lang/arturo/blob/ed0410b81b479dcf090b239e2193a45ecf65cd5d/src/library/Core.nim#L574

```text
            VNULL

    # TODO(Core/pop) should be probably renamed
    #  `pop` could easily do what a `pop` normally does, and that would mean
    #  a built-in method in the Collections module that pops/deletes an element from
    #  a given block/collection and returns it
    #
    #  This one refers to the stack and it could be quite confusing.
    #
    #  So, preferrably, IMHO, this should be renamed to something like: `unstack`, `destack`, etc
    #  label: library, enhancement, open discussion
    builtin "pop",
        alias       = unaliased, 
        op          = opNop,
```

d47a05c1d6407308255aaa295789170603758f61

### LINKED ISSUE #1083: [Core\pop] should throw an error instead of try to read from nil
**Describe the bug**

Arturo is returning SIGSEGV for build `170` when we try to `pop` more items than available in the stack.

Example: 
```red
$> 1 2 3 4 pop 5
1 2 3 4 pop 5
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

It should raises a Stack Underflow error to avoid the programmer attempt to read from `nil`. What would avoid the repl closes up and allow us to catch it with a `try?/else` structure.

Related:

> - [If you try pop 4 with 3 elements in stack, it'll return to you this error: SIGSEGV: Illegal storage access. (Attempt to read from nil?). It's the same error of any OutOfIndex in another languages.](https://discord.com/channels/765519132186640445/829324913097048065/1085691175148716122)
> - [Oh, my build just hangs.  I get no sigsegv.](https://discord.com/channels/765519132186640445/829324913097048065/1085691335027208252)

**Expected**
> [Turns out $> 1 2 3 4 pop tries to pop four things.  Only has 3 left.  I like the flexibility in Arturo.  The freeflowing in/post/pre-fix model is awesome.](https://discord.com/channels/765519132186640445/829324913097048065/1085710906735988838)
> [It should report a stack underflow and go back to the prompt, or exit out if in a script.  I think.](https://discord.com/channels/765519132186640445/829324913097048065/1085711160743051284)

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: win10/amd64
 - Version `v/0.9.83 b/170`

### PR DESCRIPTION
**Pull request by RickBarretto**
# Description

Renames the function to `unstack` and avoid it to illegally access storage causing a SIGSEGV error.

Fixes #1027 
Fixes #1083
- Related to PR #1105 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
  - Avoid attempt to read from nil #1083
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - renamed to `unstack` #1027
- [x] This change requires a documentation update
  - [x] Add/Update usage
- [x] Add/Update unit-tests

### CODE REVIEW

**Comment by RickBarretto** [comment]
Here is how it's going on:
image

**Comment by RickBarretto** [comment]
Done!
As you can see, I covered this error here: [`tests/errors/lib.core.unstack.StackUnderflow.art`](https://github.com/arturo-lang/arturo/pull/1106/files#diff-3955304a1039f98ce4d5971dd168273495177cc642e394a473e45fff8aaf947c). I can change if you see it as a problem.

**Comment by RickBarretto** [comment]
Done!
Also, I updated `console.art` too, so I will work, differently from #1105, that I couldn't do it.
I recommend merge it first, and the #1105, and if there is some conflicts, just solve it.

**Review by drkameleon — COMMENTED** [review]
Very nice job! Again!

This one was long due but... you did it! 😉 

I have just one suggestion, in order to keep things consistent:

The `RuntimeError_OperationNotPermitted` is meant to be used with operations/methods that are excluded from the *safe* builds (the *safe* builds being used exclusively in the Playground). And the idea is very simple: to "block" function that may harm the server (imagine if somebody puts code in the Playground to delete files; since the code actually runs *on* the server, this would mean we leave the door open to all sorts of attacks!)

So, what I would suggest:

- add a new error type for stack underflow, a simple on, nothing fancy, in VM/errors, like:

```
proc RuntimeError_StackUnderflow*() =
    panic RuntimeError,
            "stack underflow"
```

- Call this, instead of `RuntimeError_OperationNotPermitted` (in Core/unstack) 😉

**Comment by drkameleon** [comment]
Also, sorry for that but couldn't help it lol:  I made a tiny edit in your initial message. For some silly reason, you can't put ```Fixes #1 #2 #3```, you have to put it in separate lines, so that GitHub actually understands what you mean and close the issues after the PR is merged, but oh well... Learned this myself the hard way! :)

**Comment by RickBarretto** [comment]
> So, what I would suggest:
> - add a new error type for stack underflow, a simple on, nothing fancy, in VM/errors, like:


Sure! I'll update this!

> For some silly reason, you can't put Fixes #1 #2 #3, you have to put it in separate lines, so that GitHub actually understands what you mean and close the issues after the PR is merged, but oh well... 


Ohh, my bad! I didn't know this. Thanks for the advise! 🙂

**Review by drkameleon — APPROVED** [review]
Looking awesome! Nice and clean! 😄

**Comment by drkameleon** [comment]
Ready to merge! 🚀 

--- 

And off to merge #1105 as well! 😉

**Pull request merged**
