### PR TITLE
Creates Unit Tests for Collections module

### PR DESCRIPTION
**Pull request by RickBarretto**
# Description

This PR adds some unit tests for cover Arturo's Collection Library.

> Note: It is not complete yet. 
And I added some notes too for problems that I found and some suggestions.

## Type of change

- [x] Adds Unit Tests

### CODE REVIEW

**Comment by RickBarretto** [comment]
@drkameleon, It needs some revision.
Some functions I can't test by myself (because I don't understand if it is right or wrong, or how to use properly).
For these cases, I added some notes.

Also, I know that more than 750 lines of code can be considered a bad practice. 
So, if you want, I can put the functions inside an folder or something else, I was thinking on `lib.collections/` folder. 
I think that put every function of this file on `test/unittests/` could be as bad as it is now.

But, it's your choice, if you don't see any problem with this amount of line, it's fine too! 🙂

**Comment by drkameleon** [comment]
Wow! Awesome work! Honestly!! 😄 

I'll go through it to see what the CI builds are failing (and check the results one by one), but in any case, it looks super-fine. (And no, if I were you, I wouldn't split it into different files - after all, it's just a unit-test).

Great job! Thanks! 😉

**Comment by drkameleon** [comment]
Pff... I've been caught up with different kinds of stuff today, so I didn't have enough time to look into.

Tomorrow morning, I promise I *will* have a look and do my best to fix any pending issues & merge it! 😉

**Comment by RickBarretto** [comment]
Sure!

**Comment by drkameleon** [comment]
OK, so...

First of all, I'm amazed by the job you've done! Really good. The project definitely needs this kind of contributions! 

**What is to be done / what I have done:**

- I fixed a couple of issues (I think the main problem was the `combine` command has been renamed to `couple` - not yet documented, obviously - so that the latter performs what `combine` was used for & `combine` is solely used for combinatorics, that is: combinations). And no, I don't think you got it wrong; mostly you seem to have understood *exactly* how Arturo works! 😄 

- All of the TODOs you included are awesome, but since the GitHub plugin I'm using for processing TODOs does not yet support "unrecognized" extensions (e.g. Arturo's `.art`I will move them to the main Collections module. In any case, whether they are all valid bugs or not, this is some GREAT input; if they aren't really an issue, there's nothing to worry about; but if they are, we'll have to solve them! 😉 

So... as soon as the CI builds pass, I will merge it and proceed as I said (convert your TODOs to Collection module TODOs - which will in turn be converted into issues here on GitHub that we can track...)

Again: awesomeness! Keep going! 🚀

**Comment by drkameleon** [comment]
And... ready to merge! 🚀

**Comment by drkameleon** [comment]
As I said, I created the appropriate TODOs for all issues you mentioned & added a few tests where you weren't sure about the use (e.g. `sort.as`) or a couple more fixes (e.g. you were trying to `sort.by` a list of dictionaries, which was totally correct, only that `sort.by:'someKey [someDict anotherDict]` means the block contains the *words*, not the *values* 😉  - so you'd basically have to "evaluate" the block beforehand; in a few simple words: put a `@` before the block...)

That being said there is one issue that has confused me a bit: https://github.com/arturo-lang/arturo/issues/872 (I still opened an issue, to see what the cause may be).

This works for me fine. Could it be a Windows/MSYS2-related issue?

**Comment by RickBarretto** [comment]
> combine command has been renamed to couple

I didn't know about it. I was basing me on the official documentation website. It explains a lot LOL!

> * All of the TODOs you included are a great idea, spot-on, but since the GitHub plugin I'm using for processing TODOs [does not yet support "unrecognized" extensions](https://github.com/alstr/todo-to-issue-action/pull/105) (e.g. Arturo's `.art` - as you can see I had started a PR but then totally forgot about it...)

Sure! Next time I'll add a note and a TODO on Library's code! 💯 

> This works for me fine. Could it be a Windows/MSYS2-related issue?

I forgot to explain it better on notes (my bad!). But, here what is happening on Windows:
As you may know, Windows uses `\` to separate directories and Unix uses `/`. So, what is happening here:

image

Yep, it's mixing `\` with `/`. So, I think it may be the current error. I'll comment about it on #872 .

And... @drkameleon I got a question. What did you done to generate a working `lib.collections.res`? I tried to redirect the arturo's output to this file, but CI was failing.

**Pull request merged**
